### ISSUE TITLE
Occasional segmentation fault in BatchedMySQLDB

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1218]
```
05/May/2017 10:28:36 [NetworkInterface.cpp:1988] Started packet polling on interface wlan0 [id: 0]...
[New Thread 0x7fffbdffb700 (LWP 4171)]
[New Thread 0x7fffbd7fa700 (LWP 4172)]
05/May/2017 10:33:38 [NetworkInterface.cpp:2206] [wlan0] Found 51 aggregated flows
05/May/2017 10:38:43 [NetworkInterface.cpp:2206] [wlan0] Found 29 aggregated flows
05/May/2017 10:43:48 [NetworkInterface.cpp:2206] [wlan0] Found 77 aggregated flows
05/May/2017 10:48:53 [NetworkInterface.cpp:2206] [wlan0] Found 38 aggregated flows
05/May/2017 10:53:54 [NetworkInterface.cpp:2206] [wlan0] Found 52 aggregated flows
05/May/2017 10:58:59 [NetworkInterface.cpp:2206] [wlan0] Found 44 aggregated flows
05/May/2017 11:04:04 [NetworkInterface.cpp:2206] [wlan0] Found 53 aggregated flows
05/May/2017 11:09:09 [NetworkInterface.cpp:2206] [wlan0] Found 32 aggregated flows
05/May/2017 11:14:14 [NetworkInterface.cpp:2206] [wlan0] Found 27 aggregated flows
05/May/2017 11:19:19 [NetworkInterface.cpp:2206] [wlan0] Found 50 aggregated flows
05/May/2017 11:24:24 [NetworkInterface.cpp:2206] [wlan0] Found 31 aggregated flows
05/May/2017 11:29:29 [NetworkInterface.cpp:2206] [wlan0] Found 23 aggregated flows
05/May/2017 11:34:34 [NetworkInterface.cpp:2206] [wlan0] Found 30 aggregated flows
05/May/2017 11:39:39 [NetworkInterface.cpp:2206] [wlan0] Found 23 aggregated flows
05/May/2017 11:44:44 [NetworkInterface.cpp:2206] [wlan0] Found 33 aggregated flows
05/May/2017 11:49:44 [NetworkInterface.cpp:2206] [wlan0] Found 19 aggregated flows

Thread 1 "ntopng" received signal SIGSEGV, Segmentation fault.
0x00000000004bf22c in BatchedMySQLDBEntry::checkLen (this=0x0)
    at /home/emanuele/src/ntopng/pro/BatchedMySQLDBEntry.h:50
50	    return(available_len >= (CONST_MAX_SQL_QUERY_LEN + 1 /* comma */));
(gdb) bt
#0  0x00000000004bf22c in BatchedMySQLDBEntry::checkLen() (this=0x0)
    at /home/emanuele/src/ntopng/pro/BatchedMySQLDBEntry.h:50
#1  0x00000000004becc6 in BatchedMySQLDB::checkBufferQueue(SPSCQueue*, BatchedMySQLDBEntry*) (this=0x2c08650, q=0x2c20860, entry=0x0)
    at pro/BatchedMySQLDB.cpp:239
#2  0x00000000004bef6a in BatchedMySQLDB::dumpFlow(long, bool, Flow*, char*) (this=0x2c08650, when=1493977499, idle_flow=true, f=
    0x30b84d0, json=0x30b32d0 "{ \"8\": \"192.168.1.7\", \"12\": \"93.190.137.97\", \"7\": 0, \"11\": 125, \"4\": 6, \"57590\": 0, \"57591\": \"Unknown\", \"6\": 0, \"2\": 13, \"1\": 2146, \"24\": 16, \"23\": 2130, \"22\": 1493977497, \"21\": 1493977499, \"57595\": 0"...) at pro/BatchedMySQLDB.cpp:373
#3  0x00000000004678a5 in NetworkInterface::dumpDBFlow(long, bool, Flow*) (this=0x905920, when=1493977499, idle_flow=true, f=0x30b84d0)
    at src/NetworkInterface.cpp:625
#4  0x0000000000459626 in Flow::dumpFlow(bool) (this=0x30b84d0, idle_flow=true)
    at src/Flow.cpp:885
#5  0x000000000045a87c in Flow::update_hosts_stats(timeval*, bool) (this=0x30b84d0, tv=0x7fffffffe5b0, inDeleteMethod=true) at src/Flow.cpp:1168
#6  0x0000000000457224 in Flow::~Flow() (this=0x30b84d0, __in_chrg=<optimized out>) at src/Flow.cpp:225
#7  0x0000000000457520 in Flow::~Flow() (this=0x30b84d0, __in_chrg=<optimized out>) at src/Flow.cpp:254
#8  0x000000000040e48d in GenericHash::cleanup() (this=0xf86c40)
---Type <return> to continue, or q <return> to quit---
    at src/GenericHash.cpp:62
#9  0x000000000046d7db in NetworkInterface::periodicStatsUpdate() (this=0x905920) at src/NetworkInterface.cpp:2210
#10 0x0000000000474262 in NetworkInterface::runHousekeepingTasks() (this=0x905920) at src/NetworkInterface.cpp:4183
#11 0x00000000004adeac in Ntop::runHousekeepingTasks() (this=0x8fffd0)
    at src/Ntop.cpp:1446
#12 0x00000000004aa8f4 in Ntop::start() (this=0x8fffd0) at src/Ntop.cpp:336
#13 0x0000000000421324 in main(int, char**) (argc=11, argv=0x7fffffffea28)
    at src/main.cpp:328
```

**Comment by emanuele-f** [comment]
The cause was Flow aggregation, which is now disabled with 9e4316e5c4b43a087e25ab09a0abaf35e086ca99.
