### ISSUE TITLE
 Segmentation fault while heavy load

### ISSUE THREAD

**Issue by DatagramNetwork** [ntop/ntopng#1312]
I've compiled ntopng version:

```
v.3.1.170612 [Community Edition]
GIT rev:   dev:c516ec888a7188a7f58209aece339a308880fe18:20170612

```
Operating system: CentOS 6.9 13GB RAM, 
```
`# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 15
Model name:            Intel(R) Xeon(R) CPU           E5345  @ 2.33GHz
Stepping:              11
CPU MHz:               2333.423
BogoMIPS:              4666.70
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-7
`
```

I'm using SPAN on cisco switch to one of linux dedicated interfaces.
while span is coming from one or two vlan's everything seems to be working fine.
When I monitor all traffic ntopng is doing segmentation fault.

GDB output:
```
(gdb) run  -i eth2 --dont-change-user
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/local/bin/ntopng -i eth2 --dont-change-user
[Thread debugging using libthread_db enabled]
13/Jun/2017 13:29:01 [Ntop.cpp:1359] Setting local networks to 127.0.0.0/8
13/Jun/2017 13:29:01 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
Detaching after fork from child process 2939.
13/Jun/2017 13:29:02 [NetworkInterface.cpp:227] Executing ethtool -K eth2 gro off gso off tso off
13/Jun/2017 13:29:02 [PcapInterface.cpp:86] Reading packets from interface eth2...
13/Jun/2017 13:29:02 [Ntop.cpp:1485] Registered interface eth2 [id: 3]
13/Jun/2017 13:29:02 [main.cpp:250] PID stored in file /var/run/ntopng.pid
13/Jun/2017 13:29:02 [HTTPserver.cpp:787] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
13/Jun/2017 13:29:02 [HTTPserver.cpp:789] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
[New Thread 0x7ffff6bea700 (LWP 2940)]
[New Thread 0x7ffff61e9700 (LWP 2941)]
[New Thread 0x7ffff57e8700 (LWP 2942)]
[New Thread 0x7fffeffff700 (LWP 2943)]
[New Thread 0x7ffff4de7700 (LWP 2944)]
[New Thread 0x7fffef5fe700 (LWP 2945)]
13/Jun/2017 13:29:02 [HTTPserver.cpp:843] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
13/Jun/2017 13:29:02 [HTTPserver.cpp:846] HTTP server listening on port(s) 3000
13/Jun/2017 13:29:02 [main.cpp:311] Working directory: /var/tmp/ntopng
13/Jun/2017 13:29:02 [main.cpp:313] Scripts/HTML pages directory: /usr/local/share/ntopng
13/Jun/2017 13:29:02 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.1.170612 - (C) 1998-17 ntop.org
13/Jun/2017 13:29:02 [Ntop.cpp:312] Built on CentOS release 6.9 (Final)
13/Jun/2017 13:29:02 [PeriodicActivities.cpp:56] Started periodic activities loop...
[New Thread 0x7fffee0f3700 (LWP 2946)]
[New Thread 0x7fffed6f2700 (LWP 2947)]
[New Thread 0x7fffeccf1700 (LWP 2948)]
[New Thread 0x7fffd3fff700 (LWP 2949)]
[New Thread 0x7fffd35fe700 (LWP 2950)]
[New Thread 0x7fffd2bfd700 (LWP 2951)]
[New Thread 0x7fffd21fc700 (LWP 2952)]
13/Jun/2017 13:29:03 [NetworkInterface.cpp:2046] Started packet polling on interface eth2 [id: 3]...
[New Thread 0x7fffd17fb700 (LWP 2953)]
[New Thread 0x7fffd0dfa700 (LWP 2954)]

Program received signal SIGSEGV, Segmentation fault.
0x0000003806247c9c in vfprintf () from /lib64/libc.so.6
```

backtrace:

```
#0  0x0000003806247c9c in vfprintf () from /lib64/libc.so.6
#1  0x000000380626f5c2 in vsnprintf () from /lib64/libc.so.6
#2  0x000000380624f093 in snprintf () from /lib64/libc.so.6
#3  0x000000000044fdd5 in Flow::checkBlacklistedFlow (this=0x7fffc81ee090) at src/Flow.cpp:347
#4  0x0000000000452586 in Flow::update_hosts_stats (this=0x7fffc81ee090, tv=0x7fffffffe260) at src/Flow.cpp:1176
#5  0x00000000004aa0fd in flow_update_hosts_stats (node=0x7fffc81ee090, user_data=0x7fffffffe260) at src/NetworkInterface.cpp:2174
#6  0x000000000045e841 in GenericHash::walk (this=0x87dc20, walker=0x4aa0ca <flow_update_hosts_stats(GenericHashEntry*, void*)>, user_data=0x7fffffffe260) at src/GenericHash.cpp:155
#7  0x00000000004aa250 in NetworkInterface::periodicStatsUpdate (this=0x874500) at src/NetworkInterface.cpp:2237
#8  0x00000000004b07e0 in NetworkInterface::runHousekeepingTasks (this=0x874500) at src/NetworkInterface.cpp:4219
#9  0x00000000004ba597 in Ntop::runHousekeepingTasks (this=0x86e8c0) at src/Ntop.cpp:1499
#10 0x00000000004b739b in Ntop::start (this=0x86e8c0) at src/Ntop.cpp:350
#11 0x000000000049ced9 in main (argc=4, argv=0x7fffffffe688) at src/main.cpp:330
```

```
coredump:

GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
BFD: Warning: /root/core.2784 is truncated: expected core file size >= 208306176, found: 162308096.
BFD: Warning: /root/core.2784 is truncated: expected core file size >= 208306176, found: 162308096.
Missing separate debuginfo for the main executable file
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/dc/8610739044275266f9f4cce9ba2d029ccd8904
[New Thread 2784]
[New Thread 2800]
[New Thread 2789]
[New Thread 2793]
[New Thread 2788]
[New Thread 2796]
[New Thread 2787]
[New Thread 2791]
[New Thread 2792]
[New Thread 2799]
[New Thread 2795]
[New Thread 2797]
[New Thread 2790]
[New Thread 2798]
[New Thread 2794]
[New Thread 2786]
Failed to read a valid object file image from memory.
Core was generated by `ntopng -i eth2 --dont-change-user ---max-num-flows=20000 --max-num-hosts=2000 -'.
Program terminated with signal 11, Segmentation fault.

(gdb) backtrace
#0  0x0000003806247c9c in ?? ()
Cannot access memory at address 0x7ffc14f35ad0
```

**Comment by simonemainardi** [comment]
thanks for reporting, can you upload the core and the ntopng binary somewhere for our inspection?

**Comment by DatagramNetwork** [comment]
Hi Simon,
Please find both requested files on below link:
https://drive.google.com/drive/folders/0B3upfrz3wEjgMEhseXVPdzZDMzA?usp=sharing

**Comment by simonemainardi** [comment]
core file is trunctated:

BFD: Warning: /tmp/ntopng/core.2784 is truncated: expected core file size >= 208306176, found: 162308096.

fix this and re-upload.

Also make sure to compile using the standard ./configure && make -- don't strip symbols

**Comment by simonemainardi** [comment]
also --max-num-hosts 2000 is a very small number, increase it

**Comment by DatagramNetwork** [comment]
Hi Simon,
I've uploaded new coredump, please find it at same link.
https://drive.google.com/open?id=0B3upfrz3wEjgMEhseXVPdzZDMzA
As well I left --max-num-hosts default.

**Comment by simonemainardi** [comment]
fixed with https://github.com/ntop/ntopng/commit/5fb16927c9fc33a58b44951829d6c119c311d61c

thanks for reporting

new packages will be rebuilt overnight (CEST)
