### ISSUE TITLE
output to ES casues segfault

### ISSUE THREAD

**Issue by pcmerc** [ntop/ntopng#139]
v.2.0.150723 [Community Edition]
GIT rev:   master:0db04bee4f77fa4e96f04d27e5f50929920e0914:20150723

ntopng -i eth1 -F 'es;flows;ntopng-%Y.%m.%d;http://remoteip:9200/_bulk;'

ntopng.conf:
-i eth1
-m 192.168.1.0/24
-n 1
-e
-A 2
-H
--data-dir=/usr/local/ntopng
-G=/var/run/ntopng/ntopng.pid

ES Log:

[2015-08-26 22:29:31,962][INFO ][cluster.metadata         ] [Atlas] [ntopng-2015.08.26] creating index, cause [auto(bulk api)], shards [1]/[0], mappings [flows]
[2015-08-26 22:29:32,191][INFO ][cluster.metadata         ] [Atlas] [ntopng-2015.08.26] update_mapping [flows] (dynamic)
[2015-08-26 22:29:32,334][INFO ][cluster.metadata         ] [Atlas] [ntopng-2015.08.26] update_mapping [flows] (dynamic)

**Comment by lucaderi** [comment]
Your version is too old. Please use the code currently in git and try again

**Comment by pcmerc** [comment]
Will do, thanks Luca! :D

**Comment by lucaderi** [comment]
If not working, please paste a complete log. If working close this bug.

Thanks (please star this project on github if happy of the support)

**Comment by pcmerc** [comment]
Of course you guys get starred :D I've been using this app off & on since the Interplay days. ;)

**Comment by pcmerc** [comment]
Should I switch to Dev? The master rev looks to be the same.

**Comment by lucaderi** [comment]
Yes

**Comment by pcmerc** [comment]
What about nDPI, does that also need to be dev?
I am getting the same segfault it appears.

v.2.0.150723 [Community Edition]
GIT rev:   dev:8a23d56581a56000de1b0cc87f769937bf289cfd:20150826

**Comment by pcmerc** [comment]
][DEBUG][action.bulk              ] [Atlas] [ntopng-2015.08.27][0] failed to execute bulk item (index) index {[ntopng-2015.08.27][flows][AU9sf5HfaP2QiUwtdM2E], source[{ "IPV4_SRC_ADDR": "172.24.15.52", "L4_SRC_PORT": 54109, "IPV4_DST_ADDR": "63.140.35.166", "L4_DST_PORT": 80, "PROTOCOL": 6, "L7_PROTO": 7, "L7_PROTO_NAME": "HTTP", "TCP_FLAGS": 26, "IN_PKTS": 16, "IN_BYTES": 10502, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 1440634333, "LAST_SWITCHED": 1440634334, "SRC_VLAN": 10, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": "9x0mkhzg", "HTTP_URL": "\/b\/ss\/staplesnwprod\/1\/H.22.1\/s2894715795293?AQB=1&ndh=1&t=26%2F7%2F2015%2017%3A12%3A14%203%20420&ce=UTF-8&ns=staples&pageName=Search%20Results&g=http%3A%2F%2Fwww.staplesadvantage.com%2Fwebapp%2Fwcs%2Fstores%2Fservlet%2FStplCategoryDisplay%3FcatalogId%3D4%26langId%3D-1%26storeId%3D10101&cc=USD&events=event21&c14=sa.Autologon%3Dfalse%23%3AProp!sa.BlockOverride%3Dfalse%23%3AProp!sa.BT%3D%40B10503%23%3AProp!sa.cartCnt%3D33%23%3AProp!sa.cartSkus%3D869613%3A652595%3A917860%3A674815%3A900330%3A570951%3A853301%3A564231%3A421818%3A642736%3A503205%3A733266%3A324027%3A324053%3A324051%3A806401%3A806436%3A812997%3A480114%3A566942%3A615722%3A1311160%23%3AProp!sa.cartTot%3D%24846.83%23%3AProp!sa.div%3DDET%23%3AProp!sa.email%3Dsheila.duddridge%40mophie.com%23%3AProp!sa.errFlag%3DN%23%3AProp!sa.account%3Dsa.SupportPageUrl%3Dhttp%3A%2F%2Flinksupport%2Fwebapp%2Fwcs%2Fstores%2Fservlet%2Fsupport%2Fsupstlist.jsp%3FpageTypeST%3DpageTypeST_MA%26maNbr%3D0001611303001DET%23%3AProp!sa.Page%3DSearch%20Results%23%3AProp!sa.perfInstChat%3DN%23%3AProp!sa.ST%3DMOPHIE%20CA%23%3AProp!sa.usrGrp%3DAdministrator%23%3AProp!sa.usrID%3DCAMOPHIE%23%3AProp!sa.usrType%3DAMN&v63=sa.Autologon%3Dfalse%23%3AProp!sa.BlockOverride%3Dfalse%23%3AProp!sa.BT%3D%40B10503%23%3AProp!sa.cartCnt%3D33%23%3AProp!sa.cartSkus%3D869613%3A652595%3A917860%3A674815%3A900330%3A570951%3A853301%3A564231%3A421818%3A642736%3A503205%3A733266%3A324027%3A324053%3A324051%3A806401%3A806436%3�����\u0004�#����1��d��~����<\u0013�d�g���)���U���v�5���';�fu\u001e�\u0016�y��\u0012��yM�$Խ��#:V����\u000f-��@���7\u0018A�\u001f})�ʼ�~\u001az��Z�DUm6�\u0018J�\u0007E.\u001d��3ޙZie69\u001c\u0018�*:", "HTTP_METHOD": "GET", "HTTP_RET_CODE": 0, "@timestamp": "2015-08-27T00:12:14.0Z", "@version": 1, "type": "flows" }]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [HTTP_URL]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:709)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:500)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:410)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.jackson.core.JsonParseException: Invalid UTF-8 start byte 0x88
 at [Source: [B@6de770c7; line: 1, column: 1906]
	at org.elasticsearch.common.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._reportInvalidInitial(UTF8StreamJsonParser.java:3217)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._reportInvalidChar(UTF8StreamJsonParser.java:3211)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2238)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2165)
	at org.elasticsearch.common.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:279)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:86)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.textOrNull(AbstractXContentParser.java:194)
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:337)
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
	... 12 more

**Comment by lucaderi** [comment]
So is not ntopng that crashes, but ES that complains for invalid URL, right?

**Comment by pcmerc** [comment]
It's ES complaining that the input is not UTF-8 compliant, is what I see.

**Comment by lucaderi** [comment]
@pcmerc I have pushed a fix: can you please try it?

**Comment by pcmerc** [comment]
Updated both nDPI & ntopng, compiling now.

**Comment by pcmerc** [comment]
Compiled & running so far with no errors. I need to verify it's putting data into redis.

**Comment by pcmerc** [comment]
Very responsive now, thanks Luca. Let me know if you'd like me to do any testing on any other flavors :D

**Comment by lucaderi** [comment]
Testing is already great but @lmangani documentation is also desirable.
