### ISSUE TITLE
segfault on disaggregation

### ISSUE THREAD

**Issue by Paxy** [ntop/ntopng#1580]
Version | 3.1.171125 - Professional Edition
Ubuntu 16.04.3 LTS

When I try to enable disaggregation Ingress interface or VRF, segfault crash appear on ntopng service.
If I disable disaggregation, service works fine.

nProbe is receiving flows from Mikrotik router.

Syslog:
```
Nov 27 09:23:58 vm-ad systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Nov 27 09:23:58 vm-ad systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Nov 27 09:23:58 vm-ad ntopng[4740]: 27/Nov/2017 09:23:58 [Ntop.cpp:1482] Setting local networks to 192.168.0.0/16,217.24.20.0/27,185.181.68.0/27
Nov 27 09:23:58 vm-ad ntopng[4740]: 27/Nov/2017 09:23:58 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Nov 27 09:23:58 vm-ad ntopng[4740]: 27/Nov/2017 09:23:58 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Nov 27 09:23:58 vm-ad ntopng[4740]: 27/Nov/2017 09:23:58 [NtopPro.cpp:217] [LICENSE] Reading license from /etc/ntopng.license
Nov 27 09:23:58 vm-ad ntopng[4740]: 27/Nov/2017 09:23:58 [NtopPro.cpp:132] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]Nov 27 09:23:58 vm-ad ntopng[4740]: 27/Nov/2017 09:23:58 [NtopPro.cpp:135] [LICENSE] /etc/ntopng.license: found valid Professional license
Nov 27 09:24:02 vm-ad kernel: [19371.971085] ntopng[4740]: segfault at 149 ip 000000000048f286 sp 00007ffcf616c960 error 4 in ntopng[400000+250000]
Nov 27 09:24:02 vm-ad systemd[1]: ntopng.service: Main process exited, code=dumped, status=11/SEGV
Nov 27 09:24:02 vm-ad systemd[1]: ntopng.service: Unit entered failed state.
Nov 27 09:24:02 vm-ad systemd[1]: ntopng.service: Failed with result 'core-dump'.
Nov 27 09:24:07 vm-ad systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Nov 27 09:24:07
``` vm-ad systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.

**Comment by emanuele-f** [comment]
Can you run ntopng directly with gdb and get a stack trace please?
1) stop any running ntopng instance: `systemctl stop ntopng`
2) run ntopng: `gdb --args ntopng /etc/ntopng.conf`
3) When i crashes, execute `backtrace` to get a trace

**Comment by Paxy** [comment]
I am missing somthing !
Proccess is not started, I can not access to web interface.
```
root@vm-ad:~# ntopng /etc/ntopng/ntopng.conf
27/Nov/2017 13:52:27 [Ntop.cpp:1482] Setting local networks to 192.168.0.0/16,217.24.20.0/27,185.181.68.0/27
27/Nov/2017 13:52:27 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
27/Nov/2017 13:52:27 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
27/Nov/2017 13:52:27 [NtopPro.cpp:217] [LICENSE] Reading license from /etc/ntopng.license
27/Nov/2017 13:52:27 [NtopPro.cpp:132] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]
27/Nov/2017 13:52:27 [NtopPro.cpp:135] [LICENSE] /etc/ntopng.license: found valid Professional license
Segmentation fault (core dumped)
root@vm-ad:~# gdb --args ntopng /etc/ntopng/ntopng.conf
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ntopng...done.
(gdb)
(gdb) backtrace
No stack.

```

**Comment by emanuele-f** [comment]
After running `gdb --args ...` please enter the command `run`. It will start ntopng

**Comment by Paxy** [comment]
Oh, sorry. Here it is:
```
(gdb) run
Starting program: /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
27/Nov/2017 16:11:13 [Ntop.cpp:1482] Setting local networks to 192.168.0.0/16,217.24.20.0/27,185.181.68.0/27
27/Nov/2017 16:11:13 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
27/Nov/2017 16:11:13 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
27/Nov/2017 16:11:13 [NtopPro.cpp:217] [LICENSE] Reading license from /etc/ntopng.license
27/Nov/2017 16:11:13 [NtopPro.cpp:132] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]
27/Nov/2017 16:11:13 [NtopPro.cpp:135] [LICENSE] /etc/ntopng.license: found valid Professional license
[New Thread 0x7fffe9b5d700 (LWP 1755)]
[New Thread 0x7fffe935c700 (LWP 1756)]
[New Thread 0x7fffe8b5b700 (LWP 1757)]
[New Thread 0x7fffe3bda700 (LWP 1758)]
[New Thread 0x7fffe33d9700 (LWP 1759)]
[New Thread 0x7fffe2bd8700 (LWP 1760)]
[New Thread 0x7fffe23d7700 (LWP 1761)]
[New Thread 0x7fffe1bd6700 (LWP 1762)]
[New Thread 0x7fffe13d5700 (LWP 1763)]
[New Thread 0x7fffe0bd4700 (LWP 1764)]
[Thread 0x7fffe0bd4700 (LWP 1764) exited]
[New Thread 0x7fffe0bd4700 (LWP 1765)]
[New Thread 0x7fffc3fff700 (LWP 1766)]
[New Thread 0x7fffc37fe700 (LWP 1767)]
[New Thread 0x7fffc2ffd700 (LWP 1768)]
[New Thread 0x7fffc27fc700 (LWP 1769)]
[New Thread 0x7fffc1ffb700 (LWP 1770)]
[New Thread 0x7fffc17fa700 (LWP 1771)]
[New Thread 0x7fffc0ff9700 (LWP 1772)]
[New Thread 0x7fffc07f8700 (LWP 1773)]
[New Thread 0x7fffbfff7700 (LWP 1774)]
[New Thread 0x7fffbf7f6700 (LWP 1775)]
[New Thread 0x7fffbeff5700 (LWP 1776)]
[New Thread 0x7fffbe7f4700 (LWP 1777)]
[New Thread 0x7fffbdff3700 (LWP 1778)]
[New Thread 0x7fffbd7f2700 (LWP 1779)]
[New Thread 0x7fffbcff1700 (LWP 1780)]
[New Thread 0x7fffa7fff700 (LWP 1781)]
[New Thread 0x7fffa77fe700 (LWP 1782)]
[New Thread 0x7fffa6ffd700 (LWP 1784)]
[New Thread 0x7fffa67fc700 (LWP 1787)]

Thread 1 "ntopng" received signal SIGSEGV, Segmentation fault.
0x000000000048f286 in AlertsManager::storeFlowAlert (this=0x0, f=0x7fff9050f120, alert_type=alert_suspicious_activity,
    alert_severity=alert_level_warning,
    alert_json=0x7fffffffd9c0 "Suspicious TCP SYN Probing (or server port down): <A HREF='/lua/host_details.lua?host=217.24.20.5&ifid=3&page=alerts'>217.24.20.5</A> &gt; <A HREF='/lua/host_details.lua?host=5.9.60.241&ifid=3&page=al"...)
    at src/AlertsManager.cpp:741
741     src/AlertsManager.cpp: No such file or directory.
(gdb) backtrace
#0  0x000000000048f286 in AlertsManager::storeFlowAlert (this=0x0, f=0x7fff9050f120, alert_type=alert_suspicious_activity,
    alert_severity=alert_level_warning,
    alert_json=0x7fffffffd9c0 "Suspicious TCP SYN Probing (or server port down): <A HREF='/lua/host_details.lua?host=217.24.20.5&ifid=3&page=alerts'>217.24.20.5</A> &gt; <A HREF='/lua/host_details.lua?host=5.9.60.241&ifid=3&page=al"...)
    at src/AlertsManager.cpp:741
#1  0x00000000004213c7 in Flow::dumpFlowAlert (this=0x7fff9050f120) at src/Flow.cpp:261
#2  0x0000000000422c4a in Flow::dumpFlow (this=0x7fff9050f120, idle_flow=false) at src/Flow.cpp:801
#3  0x00000000004247db in Flow::update_hosts_stats (this=0x7fff9050f120, tv=0x7fffffffe160) at src/Flow.cpp:1219
#4  0x0000000000446d92 in flow_update_hosts_stats (node=0x7fff9050f120, user_data=0x7fffffffe160, matched=0x7fffffffe10b)
    at src/NetworkInterface.cpp:2451
#5  0x00000000004177b2 in GenericHash::walk (this=0x7fffa8013d40, begin_slot=0x7fffffffe15c, walk_all=true,
    walker=0x446d5b <flow_update_hosts_stats(GenericHashEntry*, void*, bool*)>, user_data=0x7fffffffe160)
    at src/GenericHash.cpp:163
#6  0x0000000000446f72 in NetworkInterface::periodicStatsUpdate (this=0x7fffa80118e0) at src/NetworkInterface.cpp:2522
#7  0x000000000044efea in NetworkInterface::runHousekeepingTasks (this=0x7fffa80118e0) at src/NetworkInterface.cpp:4919
#8  0x00000000004a720f in Ntop::runHousekeepingTasks (this=0x8a7130) at src/Ntop.cpp:1628
#9  0x00000000004a32ad in Ntop::start (this=0x8a7130) at src/Ntop.cpp:439
#10 0x000000000048acc8 in main (argc=2, argv=0x7fffffffe688) at src/main.cpp:402

```

**Comment by emanuele-f** [comment]
Thank you. I've committed a fix. A new package will be available in one hour.
