### ISSUE TITLE
Ntopng segfault

### ISSUE THREAD

**Issue by robynhub** [ntop/ntopng#1583]
Hello,
current stable segfault:

`# cat /etc/apt/sources.list.d/ntop.list`
```
deb http://packages.ntop.org/apt/stretch/ x64/
deb http://packages.ntop.org/apt/stretch/ all/
```

`# ntopng -V`
```
v.3.1.171130	[Enterprise/Professional build]
GIT rev:	dev:0288d5f0f4a50a418c9d941b8176d8c35817f9cc:20171130
Pro rev:	r1275
Built on:	Debian GNU/Linux 9.1 (stretch)
System Id:	BFB6D90E04001090
Platform:	x86_64
Edition:	Enterprise
License Type:	Demo
Validity:	Until Thu Nov 30 15:46:02 `2017`
```

`# cat /etc/ntopng/ntopng.conf`
```
-G /var/tmp/ntopng.pid
-i "tcp://127.0.0.1:5555c"
-d /var/tmp
-P
-u
-n 3
-l
-q
-S local
```
 
`# gdb --args ntopng /etc/ntopng/ntopng.conf`
```
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ntopng...done.
(gdb) r
Starting program: /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
30/Nov/2017 15:39:21 [Prefs.cpp:951] Localhost HTTP user login disabled
30/Nov/2017 15:39:21 [Ntop.cpp:1485] Setting local networks to 192.168.0.0/16
30/Nov/2017 15:39:21 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
30/Nov/2017 15:39:21 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
30/Nov/2017 15:39:21 [NtopPro.cpp:215] [LICENSE] Reading license from Redis
30/Nov/2017 15:39:21 [NtopPro.cpp:294] WARNING: [LICENSE] Invalid or missing license
30/Nov/2017 15:39:21 [NtopPro.cpp:311] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
30/Nov/2017 15:39:21 [NtopPro.cpp:313] WARNING: [LICENSE] before returning to community mode
30/Nov/2017 15:39:21 [NtopPro.cpp:315] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
30/Nov/2017 15:39:21 [NtopPro.cpp:317] WARNING: [LICENSE] or run ntopng in community mode starting
30/Nov/2017 15:39:21 [NtopPro.cpp:318] WARNING: [LICENSE] ntopng --community
[New Thread 0x7fffe8fde700 (LWP 2738)]
[New Thread 0x7fffe87dd700 (LWP 2739)]
30/Nov/2017 15:39:21 [Ntop.cpp:1612] Registered interface tcp://127.0.0.1:5555c [id: 4]
30/Nov/2017 15:39:21 [main.cpp:301] PID stored in file /var/tmp/ntopng.pid
30/Nov/2017 15:39:22 [HTTPserver.cpp:841] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
30/Nov/2017 15:39:22 [Utils.cpp:457] User changed to nobody
[New Thread 0x7fffe7f86700 (LWP 2740)]
[New Thread 0x7fffe7785700 (LWP 2741)]
[New Thread 0x7fffe6f84700 (LWP 2742)]
[New Thread 0x7fffe6783700 (LWP 2743)]
[New Thread 0x7fffe5f82700 (LWP 2744)]
[New Thread 0x7fffe5781700 (LWP 2745)]
30/Nov/2017 15:39:22 [HTTPserver.cpp:912] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
30/Nov/2017 15:39:22 [HTTPserver.cpp:915] HTTP server listening on port(s) 192.168.187.14:3000
30/Nov/2017 15:39:22 [main.cpp:383] Working directory: /var/tmp
30/Nov/2017 15:39:22 [main.cpp:385] Scripts/HTML pages directory: /usr/share/ntopng
30/Nov/2017 15:39:22 [Ntop.cpp:385] Welcome to ntopng x86_64 v.3.1.171130 - (C) 1998-17 ntop.org
30/Nov/2017 15:39:22 [Ntop.cpp:395] Built on Debian GNU/Linux 9.1 (stretch)
30/Nov/2017 15:39:22 [NtopPro.cpp:458] [LICENSE] System Id:	BFB6D90E04001090
30/Nov/2017 15:39:22 [NtopPro.cpp:459] [LICENSE] Edition:	Enterprise
30/Nov/2017 15:39:22 [NtopPro.cpp:460] [LICENSE] License Type:	Demo License
30/Nov/2017 15:39:22 [NtopPro.cpp:469] [LICENSE] Validity:	Until Thu Nov 30 15:49:21 2017
30/Nov/2017 15:39:22 [PeriodicActivities.cpp:51] Started periodic activities loop...
[New Thread 0x7fffe4f80700 (LWP 2746)]
[New Thread 0x7fffbffff700 (LWP 2747)]
[New Thread 0x7fffc7fff700 (LWP 2748)]
[New Thread 0x7fffc77fe700 (LWP 2749)]
[New Thread 0x7fffc6ffd700 (LWP 2750)]
[New Thread 0x7fffc67fc700 (LWP 2751)]
[New Thread 0x7fffc5ffb700 (LWP 2752)]
[New Thread 0x7fffc57fa700 (LWP 2753)]
[New Thread 0x7fffc4ff9700 (LWP 2754)]
[New Thread 0x7fffbf7fe700 (LWP 2755)]
[New Thread 0x7fffbeffd700 (LWP 2756)]
[New Thread 0x7fffbe7fc700 (LWP 2757)]
[New Thread 0x7fffbdffb700 (LWP 2758)]
[New Thread 0x7fffbd7fa700 (LWP 2759)]
[New Thread 0x7fffbcff9700 (LWP 2760)]
30/Nov/2017 15:39:34 [NetworkInterface.cpp:2320] Started packet polling on interface tcp://127.0.0.1:5555c [id: 4]...
30/Nov/2017 15:39:35 [CollectorInterface.cpp:122] Collecting flows on tcp://127.0.0.1:5555c

Thread 24 "ntopng" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbcff9700 (LWP 2760)]
0x0000555555596f2e in Mac::getDeviceType (this=0x0) at /home/deri/ntopng/include/Mac.h:103
103	/home/deri/ntopng/include/Mac.h: File o directory non esistente.
(gdb) bt
#0  0x0000555555596f2e in Mac::getDeviceType (this=0x0) at /home/deri/ntopng/include/Mac.h:103
#1  0x00005555555a2649 in Flow::updateFlowShapers (this=0x7fffb4011e00) at src/Flow.cpp:2834
#2  0x0000555555599488 in Flow::setDetectedProtocol (this=0x7fffb4011e00, proto_id=..., forceDetection=true) at src/Flow.cpp:564
#3  0x00005555555b6e50 in NetworkInterface::processFlow (this=0x555555a091e0, zflow=0x7fffbcff67b0) at src/NetworkInterface.cpp:1273
#4  0x000055555562bc2d in ParserInterface::parseSingleFlow (this=0x555555a091e0, o=0x7fffb4002110, source_id=0 '\000',
    iface=0x555555a091e0) at src/ParserInterface.cpp:939
#5  0x000055555562bd75 in ParserInterface::parseFlow (this=0x555555a091e0,
    payload=0x7fffb4000a20 "[{\"8\":\"192.168.1.12\",\"12\":\"192.168.2.12\",\"15\":\"192.168.1.12\",\"10\":21,\"14\":1,\"2\":1,\"1\":46,\"22\":1512052450,\"21\":1512052450,\"7\":0,\"11\":0,\"6\":0,\"4\":6,\"5\":40,\"16\":21100,\"17\":15705,\"9\":22,\"13\":28,\"130\":\"1"..., payload_size=4089, source_id=0 '\000', data=0x555555a091e0) at src/ParserInterface.cpp:972
#6  0x0000555555626169 in CollectorInterface::collect_flows (this=0x555555a091e0) at src/CollectorInterface.cpp:229
#7  0x0000555555626278 in packetPollLoop (ptr=0x555555a091e0) at src/CollectorInterface.cpp:260
#8  0x00007ffff6989494 in start_thread (arg=0x7fffbcff9700) at pthread_create.c:333
#9  0x00007ffff4425aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb)
```

**Comment by robynhub** [comment]
Seems to be an issue of my system. Cleared application data and it worked again.

Ty anyway
