### ISSUE TITLE
ndpiReader crash due to free?

### ISSUE THREAD

**Issue by qianguozheng** [ntop/ntopng#1592]
I use ndpiReader in openwrt router system, to monitor the traffic and it crash as below
 commit id is -- f7e95b4ee82f04704f923fd4f6608423291761d9
```
(gdb) bt
#0  free (mem=0x1040) at libc/stdlib/malloc-standard/free.c:287
#1  0x0000000000414546 in free_wrapper ()
#2  0x000000000041aa3c in ndpi_free ()
#3  0x00000000004144d3 in ndpi_free_flow_info_half ()
#4  0x000000000040c6d6 in node_idle_scan_walker ()
#5  0x000000000041a6b7 in ndpi_trecurse ()
#6  0x000000000041a72d in ndpi_trecurse ()
#7  0x000000000041a72d in ndpi_trecurse ()
#8  0x000000000041a72d in ndpi_trecurse ()
#9  0x000000000041a78b in ndpi_twalk ()
#10 0x0000000000411946 in pcap_process_packet ()
#11 0x00007f394a3363f6 in pcap_handle_packet_mmap () from /opt/richard/formal/magicwifi-gw500/branches/gam_audit/staging_dir/target-x86_64_uClibc-0.9.33.2/root-x86/usr/lib/libpcap.so.1.3
#12 0x00007f394a33653c in pcap_read_linux_mmap_v3 () from /opt/richard/formal/magicwifi-gw500/branches/gam_audit/staging_dir/target-x86_64_uClibc-0.9.33.2/root-x86/usr/lib/libpcap.so.1.3
#13 0x00007f394a336efb in pcap_loop () from /opt/richard/formal/magicwifi-gw500/branches/gam_audit/staging_dir/target-x86_64_uClibc-0.9.33.2/root-x86/usr/lib/libpcap.so.1.3
#14 0x000000000041202b in runPcapLoop ()
#15 0x00000000004121a8 in processing_thread ()
#16 0x00007f3949cffb57 in start_thread (arg=0x7f394969a770) at libpthread/nptl/pthread_create.c:295
#17 0x00007f3949cfb78e in clone () at ./libc/sysdeps/linux/x86_64/clone.S:109
#18 0x0000000000000000 in ?? ()
```

**Comment by emanuele-f** [comment]
Please open a bug here: https://github.com/ntop/nDPI/issues . If possible, please update to the latest stable/dev version before reporting the error.
