### ISSUE TITLE
Core dumping frequently

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1869]
Hi All,

Got an ntopng installation that is core dumping every 5-10 minutes. Version info:

```
root@ntop:/var/tmp# ntopng --version
v.3.4.180712    [Enterprise/Professional build]
GIT rev:        3.4-stable:fa4615f95326ff3db4ca5f59d2cee0f113a2d2d3:20180712
Pro rev:        r1596
Built on:       Ubuntu 16.04.4 LTS
System Id:      8C4D60AA9206AAF2
Platform:       x86_64
Edition:        Enterprise
License Type:   Demo
Validity:       Until Thu Jul 19 17:55:40 2018
```

I have captured a core dump and put it through gdb, and get this:

```
Core was generated by `/usr/local/bin/ntopng /run/ntopng.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004cfe59 in Host::get_visual_name (this=0x0, buf=0x7ffeb53fea90 "no-reverse-95-131-248-254.everycity.co.uk", buf_len=64, from_info=false) at src/Host.cpp:963
963     src/Host.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7f6a99cf0900 (LWP 31407))]
(gdb) bt
#0  0x00000000004cfe59 in Host::get_visual_name (this=0x0, buf=0x7ffeb53fea90 "no-reverse-95-131-248-254.everycity.co.uk", buf_len=64, from_info=false) at src/Host.cpp:963
#1  0x0000000000496eaf in AlertsManager::storeFlowAlert (this=0x5c9a700, f=0x7f6a22b22100) at src/AlertsManager.cpp:789
#2  0x000000000043ebc6 in Flow::dumpFlowAlert (this=0x7f6a22b22100) at src/Flow.cpp:256
#3  0x00000000004401de in Flow::dumpFlow (this=0x7f6a22b22100, idle_flow=false) at src/Flow.cpp:720
#4  0x0000000000442017 in Flow::update_hosts_stats (this=0x7f6a22b22100, tv=0x7ffeb53ff6c0) at src/Flow.cpp:1204
#5  0x000000000042b40e in flow_update_hosts_stats (node=0x7f6a22b22100, user_data=0x7ffeb53ff6c0, matched=0x7ffeb53ff66b) at src/NetworkInterface.cpp:2595
#6  0x0000000000417950 in GenericHash::walk (this=0x1b736a0, begin_slot=0x7ffeb53ff6b8, walk_all=true, walker=0x42b3d7 <flow_update_hosts_stats(GenericHashEntry*, void*, bool*)>, user_data=0x7ffeb53ff6c0)
    at src/GenericHash.cpp:163
#7  0x000000000042b619 in NetworkInterface::periodicStatsUpdate (this=0x1b70880) at src/NetworkInterface.cpp:2670
#8  0x0000000000433d5e in NetworkInterface::runHousekeepingTasks (this=0x1b70880) at src/NetworkInterface.cpp:5137
#9  0x00000000004ae79d in Ntop::runHousekeepingTasks (this=0x1b67130) at src/Ntop.cpp:1652
#10 0x00000000004aa769 in Ntop::start (this=0x1b67130) at src/Ntop.cpp:458
#11 0x0000000000491bf7 in main (argc=2, argv=0x7ffeb53ffbf8) at src/main.cpp:412
```

Not sure if this is related but the DNS entry no-reverse-95-131-248-254.everycity.co.uk is a reverse entry, 95.131.249.254, with no matching forward DNS entry.

If there's anything else I can do to assist, let me know! Many thanks.

**Comment by simonemainardi** [comment]
Can you please update the core dump and the ntopng binary somewhere for our inspection?

Do you see any output in the ntopng log (e.g., internal error?)

**Comment by simonemainardi** [comment]
@alaslums can you please provide the requested files?

**Comment by ghost** [comment]
Apologies for the delay, I'll get this info shortly.

**Comment by ghost** [comment]
Core file available at:

http://al.cloud.ec/core.ntopng.65534.gz

Filesize is 69MB.

Only messages are:

```
Jul 19 17:41:07 ntop kernel: [621297.457257] ntopng[32491]: segfault at aa ip 000000000040f9c4 sp 00007f75f490f8a0 error 4 in ntopng[400000+2ad000]
Jul 19 17:41:07 ntop kernel: [621297.493348] device enp1s0f0 left promiscuous mode
Jul 19 17:41:08 ntop systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Jul 19 17:41:08 ntop systemd[1]: ntopng.service: Unit entered failed state.
Jul 19 17:41:08 ntop systemd[1]: ntopng.service: Failed with result 'signal'.
Jul 19 17:41:13 ntop systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Jul 19 17:41:13 ntop systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Jul 19 17:41:13 ntop systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Jul 19 17:41:13 ntop systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Jul 19 17:41:13 ntop ntopng[32534]: 19/Jul/2018 17:41:13 [Prefs.cpp:1004] All HTTP user login disabled
Jul 19 17:41:13 ntop ntopng[32534]: 19/Jul/2018 17:41:13 [Ntop.cpp:1499] Setting local networks to 91.194.74.0/23,95.131.248.0/21,185.194.88.0/22
Jul 19 17:41:13 ntop ntopng[32534]: 19/Jul/2018 17:41:13 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
...
```

Interestingly it was happening a lot before:

```
root@ntop:/var/log# zcat syslog.6.gz | grep -v Suspicious | grep -vi alert| grep -i segfault | wc -l
102
```

However it hasn't happened in the last 6 days. I did a few things around the time it stopped crashing, such as disabling the enterprise trial version, and disabling alerts. There were vast quantities of alerts coming in, so I wonder if there was internal memory corruption.

It also looks like we're hitting the max number of flows, I'm upping that config now.

Anyway since it is no longer crashing this is a lot less urgent. Thanks for looking into it!

**Comment by cardigliano** [comment]
@alaslums are you able to provide the ntopng binary you used to generate the core? Thank you.

**Comment by simonemainardi** [comment]
@alaslums are you able to provide the binary as requested?
