### ISSUE TITLE
32bit arch support

### ISSUE THREAD

**Issue by chougulepavan** [ntop/ntopng#2344]
Hi, Will new ntopng version(3.9) support 32bit FreeBSD arch? If I compile new ntop for 32bit arch from the source will that binary work?

**Comment by emanuele-f** [comment]
Hi, no official support for 32bit OS, but if you manually compile there should be no problem

**Comment by chougulepavan** [comment]
I did try that, compiled manually but when tried to run the binary, getting a segmentation fault(core dump).

**Comment by emanuele-f** [comment]
Please see https://github.com/ntop/ntopng/blob/dev/doc/README.crash to get a stack trace. Also ensure that your are using the latest ntopng version

**Comment by chougulepavan** [comment]
Thanks Emanuele for quick followup. 
Found the problem it is because of libcrypto library, SSH required libcrypto.so.7 and ntopng require libcrypto.so.9 and as per the gdb output these library causing segmentation fault, copied gdb output below,
root@:~/build/ntopng # gdb ./ntopng
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-marcel-freebsd"...
(gdb) run
Starting program: /root/build/ntopng/ntopng 
[New LWP 100079]
[New Thread 2a403080 (LWP 100079/ntopng)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2a403080 (LWP 100079/ntopng)]
0x0823c09b in OPENSSL_ia32_cpuid ()
(gdb) bt
#0  0x0823c09b in OPENSSL_ia32_cpuid ()
#1  0x292884ab in OPENSSL_cpuid_setup () from /lib/libcrypto.so.7
#2  0x29182029 in _init () from /lib/libcrypto.so.7
#3  0x00000000 in ?? ()
(gdb)

**Comment by emanuele-f** [comment]
Ok, do you think there is something to fix our side (e.g. Makefile or conditional compilation) or this is something you can fix in your system?

**Comment by emanuele-f** [comment]
No feedback received, closing for inactivity
