### ISSUE TITLE
Invalid AggregatedFlow with nprobe causing segfault

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2426]
The following segfault appears quite soon while using nIndex and ntopng reads from a zmq socket:

```
Thread 1 "ntopng" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffea0a1040 (LWP 11263)]
0x000055555569f3b0 in NIndexFlowDB::IPv6_to_128bit (this=0x55555927cc80, v6=0x0) at pro/NIndexFlowDB.cpp:156
156	  ret = (((u_int128_t)(v6->u6_addr.u6_addr32[3])) << 96)
(gdb) bt
#0  0x000055555569f3b0 in NIndexFlowDB::IPv6_to_128bit(ndpi_in6_addr*) (this=0x55555927cc80, v6=0x0) at pro/NIndexFlowDB.cpp:156
#1  0x000055555569fc89 in NIndexFlowDB::dumpAggregatedFlow(long, AggregatedFlow*, bool, bool, bool) (this=0x55555927cc80, when=1551264265, f=
    0x5555596bd0c0, is_top_aggregated_flow=true, is_top_cli=true, is_top_srv=true) at pro/NIndexFlowDB.cpp:350
#2  0x00005555555ea854 in NetworkInterface::dumpAggregatedFlow(long, AggregatedFlow*, bool, bool, bool) (this=
    0x55555595a700, when=1551264265, f=0x5555596bd0c0, is_top_aggregated_flow=true, is_top_cli=true, is_top_srv=true) at src/NetworkInterface.cpp:699
#3  0x000055555567f72a in AggregatedFlowHash::cleanup() (this=0x555555e57e70) at pro/AggregatedFlowHash.cpp:175
#4  0x00005555555f2cc5 in NetworkInterface::periodicStatsUpdate() (this=0x55555595a700) at src/NetworkInterface.cpp:2887
#5  0x00005555555fbade in NetworkInterface::runHousekeepingTasks() (this=0x55555595a700) at src/NetworkInterface.cpp:5368
#6  0x0000555555641240 in Ntop::runHousekeepingTasks() (this=0x55555592c300) at src/Ntop.cpp:2047
#7  0x000055555563ba81 in Ntop::start() (this=0x55555592c300) at src/Ntop.cpp:486
#8  0x000055555566ebfb in main(int, char**) (argc=11, argv=0x7fffffffea28) at src/main.cpp:396
(gdb) frame 1
#1  0x000055555569fc89 in NIndexFlowDB::dumpAggregatedFlow (this=0x55555927cc80, when=1551264265, f=0x5555596bd0c0, is_top_aggregated_flow=true, is_top_cli=true, is_top_srv=true) at pro/NIndexFlowDB.cpp:350
(gdb) p *f
$6 = {<GenericHashEntry> = {_vptr.GenericHashEntry = 0x55555588cfc0 <vtable for AggregatedFlow+16>, hash_next = 0x0, num_uses = 0, will_be_purged = false, first_seen = 1551263899, last_seen = 1551264018, 
    iface = 0x55555595a700}, cli_ip = {addr = {ipVersion = 0 '\000', localHost = 0 '\000', privateIP = 0 '\000', multicastIP = 0 '\000', broadcastIP = 0 '\000', notUsed = 0 '\000', ipType = {ipv6 = {u6_addr = {
            u6_addr8 = '\000' <repeats 15 times>, u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, u6_addr32 = {0, 0, 0, 0}}}, ipv4 = 0}}, ip_key = 0}, srv_ip = {addr = {ipVersion = 0 '\000', localHost = 0 '\000', 
      privateIP = 0 '\000', multicastIP = 0 '\000', broadcastIP = 0 '\000', notUsed = 0 '\000', ipType = {ipv6 = {u6_addr = {u6_addr8 = '\000' <repeats 15 times>, u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, 
            u6_addr32 = {0, 0, 0, 0}}}, ipv4 = 0}}, ip_key = 0}, vlanId = 0, l4_protocol = 6 '\006', l7_protocol = 185, num_aggregated_flows = 1, num_anomalous_status_flows = 0, cli2srv_packets = 54, 
  srv2cli_packets = 36, cli2srv_bytes = 5592, srv2cli_bytes = 4688}
```

**Comment by emanuele-f** [comment]
nprobe startup line:

```sudo ./nprobes -i wlan0 -n none --zmq "tcp://127.0.0.1:5556" --disable-cache --zmq-disable-buffering -T "@NTOPNG@ %IN_SRC_MAC %OUT_SRC_MAC %IN_DST_MAC %OUT_DST_MAC %IPV4_SRC_ADDR %IPV6_SRC_ADDR %IP_PROTOCOL_VERSION %IPV4_DST_ADDR %IPV6_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %SRC_VLAN %DST_VLAN %DOT1Q_SRC_VLAN %DOT1Q_DST_VLAN %L7_PROTO %PROTOCOL %TCP_FLAGS %INITIATOR_PKTS %IN_PKTS %INITIATOR_OCTETS %IN_BYTES %RESPONDER_PKTS %OUT_PKTS %RESPONDER_OCTETS %OUT_BYTES %OOORDER_IN_PKTS %OOORDER_OUT_PKTS %RETRANSMITTED_IN_PKTS %RETRANSMITTED_OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED %SAMPLING_INTERVAL %DIRECTION %NPROBE_IPV4_ADDRESS %EXPORTER_IPV4_ADDRESS %INPUT_SNMP %OUTPUT_SNMP %POST_NAT_SRC_IPV4_ADDR %POST_NAT_DST_IPV4_ADDR %POST_NAPT_SRC_TRANSPORT_PORT %POST_NAPT_DST_TRANSPORT_PORT %SRC_PROC_PID %SRC_PROC_NAME %SRC_PROC_USER_NAME %SRC_FATHER_PROC_PID %SRC_FATHER_PROC_NAME %SRC_PROC_ACTUAL_MEMORY %SRC_PROC_PEAK_MEMORY %SRC_PROC_AVERAGE_CPU_LOAD %SRC_PROC_NUM_PAGE_FAULTS %SRC_PROC_PCTG_IOWAIT %DST_PROC_PID %DST_PROC_NAME %DST_PROC_USER_NAME %DST_FATHER_PROC_PID %DST_FATHER_PROC_NAME %DST_PROC_ACTUAL_MEMORY %DST_PROC_PEAK_MEMORY %DST_PROC_AVERAGE_CPU_LOAD %DST_PROC_NUM_PAGE_FAULTS %DST_PROC_PCTG_IOWAIT %DNS_QUERY %HTTP_URL %HTTP_SITE %SSL_SERVER_NAME %BITTORRENT_HASH %IPV4_NEXT_HOP %IPV4_SRC_MASK %IPV4_DST_MASK %INGRESS_VRFID"```

**Comment by simonemainardi** [comment]
can't reproduce. Are you able to debug?

**Comment by emanuele-f** [comment]
Can't reproduce now. I've added some code to check invalid flows and print an error message to avoid crashes
