### ISSUE TITLE
ntopng v.3.9.190314 segfaults on raspberry pi

### ISSUE THREAD

**Issue by anubisg1** [ntop/ntopng#2461]
```
root@dns1 /etc/ntopng # ntopng --version
v.3.9.190314    [Enterprise/Professional/Embedded build]
GIT rev:        dev:b41eeffba7c5533174d65a7f1a6366538851ba14:20190314
Pro rev:        r2281
Built on:       Raspbian GNU/Linux 9.1 (stretch)
System Id:      FD901A83499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited
Validity:       Until Sat Mar 16 11:53:58 2019
License:        F252843927DCE2F0F2C42FE05332D0011494579179A59C7D2E
```

```
root@dns1 /etc/ntopng # gdb ntopng
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ntopng...done.
(gdb) run
Starting program: /usr/local/bin/ntopng
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
16/Mar/2019 11:42:46 [Ntop.cpp:1982] Setting local networks to 127.0.0.0/8
16/Mar/2019 11:42:46 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
16/Mar/2019 11:42:46 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
16/Mar/2019 11:42:46 [NtopPro.cpp:313] [LICENSE] Reading license from /etc/ntopng.license
16/Mar/2019 11:42:46 [NtopPro.cpp:205] [LICENSE] /etc/ntopng.license: unable to validate Enterprise Embedded license [License mismatch error]
16/Mar/2019 11:42:46 [NtopPro.cpp:205] [LICENSE] /etc/ntopng.license: unable to validate Professional Embedded license [Unable to unlock this version (maintenance expired)]
16/Mar/2019 11:42:46 [NtopPro.cpp:311] [LICENSE] Reading license from Redis
16/Mar/2019 11:42:46 [NtopPro.cpp:205] [LICENSE] F252843927DCE2F0F2C42FE05332D0011494579179A59C7D2E: unable to validate Enterprise Embedded license [License mismatch error]
16/Mar/2019 11:42:46 [NtopPro.cpp:205] [LICENSE] F252843927DCE2F0F2C42FE05332D0011494579179A59C7D2E: unable to validate Professional Embedded license [Unable to unlock this version (maintenance expired)]
16/Mar/2019 11:42:46 [NtopPro.cpp:452] WARNING: [LICENSE] Invalid or missing license
16/Mar/2019 11:42:46 [NtopPro.cpp:469] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
16/Mar/2019 11:42:46 [NtopPro.cpp:471] WARNING: [LICENSE] before returning to community mode
16/Mar/2019 11:42:46 [NtopPro.cpp:473] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
16/Mar/2019 11:42:46 [NtopPro.cpp:475] WARNING: [LICENSE] or run ntopng in community mode starting
16/Mar/2019 11:42:46 [NtopPro.cpp:476] WARNING: [LICENSE] ntopng --community

Program received signal SIGSEGV, Segmentation fault.
lh_char_hash (k=0x4) at linkhash.c:47
47      linkhash.c: No such file or directory.
(gdb) bt
#0  lh_char_hash (k=0x4) at linkhash.c:47
#1  0x001a3934 in lh_table_lookup_entry (t=0xb91e08, k=0x4) at linkhash.c:160
#2  0x001a39f8 in lh_table_lookup_ex (t=<optimized out>, k=<optimized out>, v=0x7effeba0) at linkhash.c:185
#3  0x000ed39c in nDPIStats::deserialize (this=0xb87050, iface=0x235990, o=0xb91c50) at src/nDPIStats.cpp:296
#4  0x0011c080 in HostPoolStats::deserialize (this=0xb86ef0, iface=0x235990, o=0xb916b8) at pro/HostPoolStats.cpp:101
#5  0x0003f934 in HostPools::loadFromRedis (this=0xb82e18) at src/HostPools.cpp:363
#6  0x0003c8dc in HostPools::HostPools (this=0xb82e18, _iface=0x235990) at src/HostPools.cpp:79
#7  0x0004afa0 in NetworkInterface::NetworkInterface (this=0x235990, name=0x1b6228 "dummy", custom_interface_type=0x0) at src/NetworkInterface.cpp:237
#8  0x000adc88 in Prefs::add_default_interfaces (this=0x2318f8) at src/Prefs.cpp:1575
#9  0x0009e6bc in main (argc=1, argv=0x7efff774) at src/main.cpp:148
```

**Comment by anubisg1** [comment]
version 3.9.190208 does not crash, what ever is causing the crash was introduced between 3.9.190208 and 3.9.190314

**Comment by LunkwillAndFook** [comment]
I am experiencing the same issue. I will try downgrading to 3.9.190208 to confirm whether that works.

**Comment by Tijah82** [comment]
I have the same problem with the version ntopng_3.9.190314-6347_armhf.deb. I have reinstalled the previous version and it works very well.

**Comment by emanuele-f** [comment]
Fixed in https://github.com/ntop/nDPI/commit/6c9fbc2ddb9bbdc054580ff6dd4e7f5b7ea8a452 . A new package will be available in two hours.
