### ISSUE TITLE
Crash with too many alerts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2980]
When enabling an alert for all hosts, ntopng experiences sporadic crashes:

```
[Thread 0x7fffb6ff5700 (LWP 20509) exited]
[New Thread 0x7fffb6ff5700 (LWP 20510)]
[Thread 0x7fffb6ff5700 (LWP 20510) exited]
double free or corruption (out)

Thread 11 "TrPoolWorker" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffc8a97700 (LWP 20360)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
```

**Comment by simonemainardi** [comment]
This is the stacktrace:

```
[Thread 0x7fffb6ff5700 (LWP 20992) exited]
corrupted size vs. prev_size while consolidating

Thread 13 "TrPoolWorker" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffc2289700 (LWP 20554)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6bca7bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6bb5535 in __GI_abort () at abort.c:79
#2  0x00007ffff6c0c508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6d1728d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6c12c1a in malloc_printerr (str=str@entry=0x7ffff6d19068 "corrupted size vs. prev_size while consolidating") at malloc.c:5341
#4  0x00007ffff6c14896 in _int_free (av=0x7fff70000020, p=0x7ffc35f26290, have_lock=<optimized out>) at malloc.c:4324
#5  0x0000555555646b1a in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > >::deallocate(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >*, unsigned long) (this=0x7ffcc7a377c8, __p=0x7ffc35f263c0) at /usr/include/c++/8/ext/new_allocator.h:125
#6  0x000055555564687d in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > > >::deallocate(std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > >&, std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >*, unsigned long) (__a=..., __p=0x7ffc35f263c0, __n=1)
    at /usr/include/c++/8/bits/alloc_traits.h:462
#7  0x0000555555645f4d in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > >::_M_put_node(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >*) (this=0x7ffcc7a377c8, __p=0x7ffc35f263c0) at /usr/include/c++/8/bits/stl_tree.h:603
#8  0x00005555556450ae in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > >::_M_drop_node(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >*) (this=0x7ffcc7a377c8, __p=0x7ffc35f263c0) at /usr/include/c++/8/bits/stl_tree.h:670
#9  0x0000555555645810 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > >::_M_erase_aux(std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >)Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<struct std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert>>.:
 (this=0x7ffcc7a377c8, __position=...) at /usr/include/c++/8/bits/stl_tree.h:2493
#10 0x0000555555644e02 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >)Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<struct std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert>>.:
 (this=0x7ffcc7a377c8, __position=...) at /usr/include/c++/8/bits/stl_tree.h:1141
#11 0x0000555555644837 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Alert, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert> >)Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<struct std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Alert>>.:
 (this=0x7ffcc7a377c8, __position=...)
    at /usr/include/c++/8/bits/stl_map.h:1037
#12 0x0000555555643988 in AlertableEntity::releaseAlert(lua_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ScriptPeriodicity, long) (this=0x7ffcc7a37670, vm=0x7fff78631f78, key="2@min_bytes", p=minute_script, now=1571751320)
    at src/AlertableEntity.cpp:148
#13 0x00005555556244f9 in ntop_release_triggered_alert(lua_State*, AlertableEntity*, int) (vm=0x7fff78631f78, alertable=0x7ffcc7a37670, idx=4) at src/LuaEngine.cpp:9374
#14 0x00005555556245f0 in ntop_host_release_triggered_alert(lua_State*) (vm=0x7fff78631f78) at src/LuaEngine.cpp:9390
#15 0x00005555556eef17 in luaD_precall.part.3 ()
#16 0x00005555556f9f95 in luaV_execute ()
#17 0x00005555556ef178 in luaD_call ()
#18 0x00005555556ef1a1 in luaD_callnoyield ()
#19 0x00005555556ee5ef in luaD_rawrunprotected ()
#20 0x00005555556ef4ab in luaD_pcall ()
#21 0x00005555556eca96 in lua_pcallk ()
#22 0x000055555562e03e in AlertCheckLuaEngine::pcall(int, int) (this=0x7fffc22880d0, num_args=1, num_results=0) at src/AlertCheckLuaEngine.cpp:114
#23 0x00005555556741c8 in handle_entity_alerts(AlertCheckLuaEngine*, AlertableEntity*) (acle=0x7fffc22880d0, entity=0x7ffcc7a37670) at src/NetworkInterface.cpp:7505
#24 0x0000555555674227 in host_alert_check(GenericHashEntry*, void*, bool*) (h=0x7ffcc7a37640, user_data=0x7fffc22880d0, matched=0x7fffc228802e) at src/NetworkInterface.cpp:7515
#25 0x000055555564d4aa in GenericHash::walk(unsigned int*, bool, bool (*)(GenericHashEntry*, void*, bool*), void*, bool) (this=0x5555560e4ff0, begin_slot=0x7fffc22881ec, walk_all=true, walker=
    0x5555556741cb <host_alert_check(GenericHashEntry*, void*, bool*)>, user_data=0x7fffc22880d0, walk_idle=false) at src/GenericHash.cpp:126
#26 0x000055555565dd4a in NetworkInterface::walker(unsigned int*, bool, WalkerType, bool (*)(GenericHashEntry*, void*, bool*), void*, bool) (this=0x555555c0d560, begin_slot=0x7fffc22881ec, walk_all=true, wtype=walker_hosts, walker=
    0x5555556741cb <host_alert_check(GenericHashEntry*, void*, bool*)>, user_data=0x7fffc22880d0, walk_idle=false) at src/NetworkInterface.cpp:886
#27 0x00005555556742dc in NetworkInterface::checkHostsAlerts(ScriptPeriodicity) (this=0x555555c0d560, p=minute_script) at src/NetworkInterface.cpp:7531
#28 0x000055555561005e in ntop_check_hosts_alerts(lua_State*, ScriptPeriodicity) (vm=0x7fff79d8f1f8, p=minute_script) at src/LuaEngine.cpp:2504
#29 0x000055555561008e in ntop_check_hosts_alerts_min(lua_State*) (vm=0x7fff79d8f1f8) at src/LuaEngine.cpp:2510
#30 0x00005555556eef17 in luaD_precall.part.3 ()
#31 0x00005555556f9f95 in luaV_execute ()
#32 0x00005555556ef178 in luaD_call ()
#33 0x00005555556ef1a1 in luaD_callnoyield ()
#34 0x00005555556ee5ef in luaD_rawrunprotected ()
#35 0x00005555556ef4ab in luaD_pcall ()
#36 0x00005555556eca96 in lua_pcallk ()
#37 0x00005555556ae3c2 in LuaHandler::luaL_dofileM(bool) (this=0x7fff7977efd0, execute=true) at pro/LuaHandler.cpp:32
#38 0x0000555555625c8e in __ntop_lua_handlefile(lua_State*, char*, bool) (L=0x7fff79d8f1f8, script_path=0x7fff84000ba0 "/usr/share/ntopng/scripts/callbacks/interface/minute.lua", ex=true) at src/LuaEngine.cpp:9861
#39 0x0000555555626f80 in LuaEngine::run_script(char*, NetworkInterface*, bool) (this=0x7fff790a4b10, script_path=0x7fff84000ba0 "/usr/share/ntopng/scripts/callbacks/interface/minute.lua", iface=0x555555c0d560, load_only=false) at src/LuaEngine.cpp:10826
#40 0x00005555555f059b in ThreadedActivity::runScript(char*, NetworkInterface*) (this=0x555581db4af0, script_path=0x7fff84000ba0 "/usr/share/ntopng/scripts/callbacks/interface/minute.lua", iface=0x555555c0d560) at src/ThreadedActivity.cpp:181
#41 0x0000555555649b07 in ThreadPool::run() (this=0x5555820baa30) at src/ThreadPool.cpp:95
--Type <RET> for more, q to quit, c to continue without paging--
#42 0x00005555556497ff in doRun(void*) (ptr=0x5555820baa30) at src/ThreadPool.cpp:31
#43 0x00007ffff764afa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#44 0x00007ffff6c8c4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by simonemainardi** [comment]
Fixed with https://github.com/ntop/ntopng/commit/ff3469d8973a6e3a075a3e9f3affb23e1146af9e
