### ISSUE TITLE
make minify fails

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3166]
Tried to edit `plugin-script-datatable.js` and re-run `make minify` but it fails:

```
simone@devel:~/ntopng$ make minify
cd httpdocs/js; make UGLIFY_VERSION=2 minify
make[1]: Entering directory '/home/simone/ntopng/httpdocs/js'
uglifyjs -o ntop.min.js --source-map ntop.min.js.map -- datatable_utils.js ays_utils.js ntopng_utils.js graph_utils.js ebpf_utils.js ntopng_validators.js plugin-script-datatable.js
Parse error at plugin-script-datatable.js:12,16
Unexpected token: name (count)
Error
    at new JS_Parse_Error (/usr/lib/nodejs/uglify-js/lib/parse.js:189:18)
    at js_error (/usr/lib/nodejs/uglify-js/lib/parse.js:197:11)
    at croak (/usr/lib/nodejs/uglify-js/lib/parse.js:656:9)
    at token_error (/usr/lib/nodejs/uglify-js/lib/parse.js:664:9)
    at unexpected (/usr/lib/nodejs/uglify-js/lib/parse.js:670:9)
    at semicolon (/usr/lib/nodejs/uglify-js/lib/parse.js:690:43)
    at simple_statement (/usr/lib/nodejs/uglify-js/lib/parse.js:864:73)
    at /usr/lib/nodejs/uglify-js/lib/parse.js:737:19
    at /usr/lib/nodejs/uglify-js/lib/parse.js:703:24
    at block_ (/usr/lib/nodejs/uglify-js/lib/parse.js:977:20)
Makefile:35: recipe for target 'ntop.min.js' failed
make[1]: *** [ntop.min.js] Error 1
make[1]: Leaving directory '/home/simone/ntopng/httpdocs/js'
Makefile:258: recipe for target 'minify' failed
make: *** [minify] Error 2
```

**Comment by gabryon99** [comment]
Thanks for the report. To minify the `plugin-script-datable.js` you have to make sure to have installated `uglify-es` because the script uses ES6 standards which are not support by uglify-js standard. You can find `uglify-es` in npm repositories. Then you have to type `make minify UGLIFY_VERSION=3` because as the npm page says the `es` version is s API/CLI compatible with `uglify-js@3`.

https://www.npmjs.com/package/uglify-es

**Comment by simonemainardi** [comment]
please update the README.compilation and commit the necessary changes to the makefile so that `make minify` can complete without errors and without extra params such as `UGLIFY_VERSION=3`

**Comment by gabryon99** [comment]
Issue fixed: https://github.com/ntop/ntopng/pull/3169
