### ISSUE TITLE
ntopng service is constantly restarting

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3382]
i, after the last update to 3.9.200204, ntopng service is constantly restarting.

My system is Ubuntu-18.04 on ZFS, ntopng is writing to influxdb for Grafana support.

I've tried to update to 3.9.200205, but the same behaviour occurs.

A grep on ntopng.service in /var/log/syslog shows:

Feb 5 09:39:26 riemann systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Feb 5 09:39:26 riemann systemd[1]: ntopng.service: Failed with result 'signal'.
Feb 5 09:39:31 riemann systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Feb 5 09:39:31 riemann systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 63.
Feb 5 09:41:45 riemann systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Feb 5 09:41:45 riemann systemd[1]: ntopng.service: Failed with result 'signal'.
Feb 5 09:41:51 riemann systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Feb 5 09:41:51 riemann systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 64.
Feb 5 09:42:33 riemann systemd[1]: ntopng.service: Main process exited, code=killed, status=6/ABRT
Feb 5 09:42:33 riemann systemd[1]: ntopng.service: Failed with result 'signal'.
Feb 5 09:42:39 riemann systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Feb 5 09:42:39 riemann systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 65.
Feb 5 09:44:00 riemann systemd[1]: ntopng.service: Main process exited, code=killed, status=6/ABRT
Feb 5 09:44:00 riemann systemd[1]: ntopng.service: Failed with result 'signal'.
Feb 5 09:44:05 riemann systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Feb 5 09:44:05 riemann systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 66.
Feb 5 09:44:36 riemann systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Feb 5 09:44:36 riemann systemd[1]: ntopng.service: Failed with result 'signal'.
Feb 5 09:44:41 riemann systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Feb 5 09:44:41 riemann systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 67.
Feb 5 09:45:43 riemann systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Feb 5 09:45:43 riemann systemd[1]: ntopng.service: Failed with result 'signal'.
Feb 5 09:45:49 riemann systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Feb 5 09:45:49 riemann systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 68.
Feb 5 09:46:21 riemann systemd[1]: ntopng.service: Main process exited, code=killed, status=6/ABRT
Feb 5 09:46:21 riemann systemd[1]: ntopng.service: Failed with result 'signal'.
Feb 5 09:46:26 riemann systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Feb 5 09:46:26 riemann systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 69.

Before it restarts, a kernel message appears like this:

Feb 5 09:52:40 riemann kernel: [ 5964.011529] traps: inline ifid 1[2681] general protection ip:56528d0f6e34 sp:7ff367ffe490 error:0 in ntopng[56528d07e000+3ff000]
...
Feb 5 10:03:30 riemann kernel: [ 6614.618745] traps: stats_update.lu[25859] general protection ip:55fdad391d6c sp:7f2d79fd83b0 error:0 in ntopng[55fdad316000+3ff000]
...
Feb 5 10:04:59 riemann kernel: [ 6703.945659] inline ifid 1[30412]: segfault at 7ff229157d7d ip 0000560ac3b1d7e3 sp 00007ff264ff8110 error 4 in ntopng[560ac3931000+3ff000]
...
Feb 5 10:09:13 riemann kernel: [ 6957.775909] traps: inline ifid 1[32179] general protection ip:55ec0c468e34 sp:7f89b4ff8008 error:0 in ntopng[55ec0c3f0000+3ff000]
...
Feb 5 10:11:32 riemann ntopng[8589]: free(): invalid next size (normal)
...
Feb 5 10:12:08 riemann kernel: [ 7132.003575] traps: inline ifid 1[13615] general protection ip:560c5e2d4e34 sp:7f4c627fb490 error:0 in ntopng[560c5e25c000+3ff000]

**Comment by simonemainardi** [comment]
seems issue is with nDPI TLS

```
#0  0x00007fd0cbc9de97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fd0cbc9f801 in __GI_abort () at abort.c:79
#2  0x00007fd0cbce8897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fd0cbe15b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fd0cbcef90a in malloc_printerr (str=str@entry=0x7fd0cbe177a8 "munmap_chunk(): invalid pointer") at malloc.c:5350
#4  0x00007fd0cbcf6ecc in munmap_chunk (p=0x7fd0453754f0) at malloc.c:2846
#5  0x00007fd0cbcf6ecc in __GI___libc_free (mem=0x7fd045375500) at malloc.c:3117
#6  0x0000564ba9e24bb0 in ndpi_realloc (ptr=0x7fd045375500, old_size=2048, new_size=new_size@entry=3532) at ndpi_main.c:131
#7  0x0000564ba9e3b44e in ndpi_search_tls_tcp_memory (ndpi_struct=ndpi_struct@entry=0x564bafa01fb0, flow=flow@entry=0x7fd04536db20) at protocols/tls.c:137
#8  0x0000564ba9e3c5f9 in ndpi_search_tls_tcp (ndpi_struct=0x564bafa01fb0, flow=0x7fd04536db20) at protocols/tls.c:512
#9  0x0000564ba9e2f7b3 in check_ndpi_tcp_flow_func (ndpi_str=0x564bafa01fb0, flow=0x7fd04536db20, ndpi_selection_packet=0x7fd084ff8288) at ndpi_main.c:4121
#10 0x0000564ba9e301c0 in ndpi_detection_process_packet (ndpi_str=0x564bafa01fb0, flow=0x7fd04536db20, packet=<optimized out>, packetlen=<optimized out>, current_tick_l=<optimized out>, src=0x7fd04536e3e0, dst=0x7fd04536e500) at ndpi_main.c:4871
#11 0x0000564ba9dc4af2 in NetworkInterface::processPacket(unsigned int, bool, timeval const*, unsigned long, ndpi_ethhdr*, unsigned short, ndpi_iphdr*, ndpi_ipv6hdr*, unsigned short, unsigned int, pcap_pkthdr const*, unsigned char const*, unsigned short*, Host**, Host**, Flow**) (this=
    0x564baaeadcc0, bridge_iface_idx=1, ingressPacket=true, when=0x7fd084ff87d0, packet_time=1580903495234, eth=0x7fd0bbc8e7f4, vlan_id=0, iph=0x7fd0bbc8e802, ip6=0x0, ip_offset=14, len_on_wire=182, h=0x7fd084ff87d0, packet=0x7fd0bbc8e7f4 <error: Cannot access memory at address 0x7fd0bbc8e7f4>, ndpiProtocol=0x7fd084ff8792, srcHost=0x7fd084ff87a8, dstHost=0x7fd084ff87b0, hostFlow=0x7fd084ff87b8) at src/NetworkInterface.cpp:1412
#12 0x0000564ba9dc68a3 in NetworkInterface::dissectPacket(unsigned int, bool, unsigned char*, pcap_pkthdr const*, unsigned char const*, unsigned short*, Host**, Host**, Flow**) (this=0x564baaeadcc0, bridge_iface_idx=1, ingressPacket=true, sender_mac=0x0, h=0x7fd084ff87d0, packet=0x7fd0bbc8e7f4 <error: Cannot access memory at address 0x7fd0bbc8e7f4>, ndpiProtocol=0x7fd084ff8792, srcHost=0x7fd084ff87a8, dstHost=0x7fd084ff87b0, flow=0x7fd084ff87b8) at src/NetworkInterface.cpp:1979
#13 0x0000564ba9deecc6 in PF_RINGInterface::singlePacketPollLoop() (this=0x564baaeadcc0) at src/PF_RINGInterface.cpp:158
#14 0x0000564ba9def139 in packetPollLoop(void*) (ptr=0x564baaeadcc0) at src/PF_RINGInterface.cpp:240
#15 0x00007fd0ce4876db in start_thread (arg=0x7fd084ff9700) at pthread_create.c:463
#16 0x00007fd0cbd8088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 8
#8  0x0000564ba9e3c5f9 in ndpi_search_tls_tcp (ndpi_struct=0x564bafa01fb0, flow=0x7fd04536db20) at protocols/tls.c:512
512	protocols/tls.c: No such file or directory.
(gdb)
```

**Comment by simonemainardi** [comment]
Possibly fixed in https://github.com/ntop/nDPI/commit/a3da5604a38a1b2b240a9d692dade086148eb2e4

Waiting for user feedback before closing.

**Comment by simonemainardi** [comment]
user confirmed the issue is fixed.
