### ISSUE TITLE
Crash in ~nDPIStats

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3386]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7604c51101 in free () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f758a0d2700 (LWP 31776))]
Missing separate debuginfos, use: yum debuginfo-install brotli-1.0.6-1.el8.x86_64 bzip2-libs-1.0.6-26.el8.x86_64 cairo-1.15.12-3.el8.x86_64 cyrus-sasl-lib-2.1.27-1.el8.x86_64 expat-2.2.5-3.el8.x86_64 fontconfig-2.13.1-3.el8.x86_64 freetype-2.9.1-4.el8.x86_64 fribidi-1.0.4-7.el8_1.x86_64 glib2-2.56.4-7.el8.x86_64 glibc-2.28-72.el8.x86_64 gmp-6.1.2-10.el8.x86_64 gnutls-3.6.8-8.el8.x86_64 harfbuzz-1.7.5-3.el8.x86_64 hiredis-0.13.3-11.el8.x86_64 json-c-0.13.1-0.2.el8.x86_64 keyutils-libs-1.5.10-6.el8.x86_64 krb5-libs-1.17-9.el8.x86_64 libX11-1.6.7-1.el8.x86_64 libXau-1.0.8-13.el8.x86_64 libXext-1.3.3-9.el8.x86_64 libXrender-0.9.10-7.el8.x86_64 libblkid-2.32.1-17.el8.x86_64 libcap-2.26-1.el8.x86_64 libcom_err-1.44.6-3.el8.x86_64 libcurl-7.61.1-11.el8.x86_64 libdatrie-0.2.9-7.el8.x86_64 libffi-3.1-21.el8.x86_64 libgcc-8.3.1-4.5.el8.x86_64 libidn2-2.2.0-1.el8.x86_64 libmaxminddb-1.2.0-6.el8.x86_64 libnghttp2-1.33.0-1.el8_0.1.x86_64 libpng-1.6.34-5.el8.x86_64 libpsl-0.20.2-5.el8.x86_64 libselinux-2.9-2.1.el8.x86_64 libsodium-1.0.18-2.el8.x86_64 libssh-0.9.0-4.el8.x86_64 libstdc++-8.3.1-4.5.el8.x86_64 libtasn1-4.13-3.el8.x86_64 libthai-0.1.27-2.el8.x86_64 libunistring-0.9.9-3.el8.x86_64 libunwind-1.3.1-3.el8.x86_64 libxcb-1.13-5.el8.x86_64 libxcrypt-4.1.1-4.el8.x86_64 libxml2-2.9.7-5.el8.x86_64 libzstd-1.4.4-1.el8.x86_64 mysql-libs-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 nettle-3.4.1-1.el8.x86_64 openldap-2.4.46-10.el8.x86_64 openpgm-5.2.122-21.el8.x86_64 openssl-libs-1.1.1c-2.el8.x86_64 p11-kit-0.23.14-5.el8_0.x86_64 pango-1.42.4-6.el8.x86_64 pcre-8.42-4.el8.x86_64 pcre2-10.32-1.el8.x86_64 pixman-0.36.0-1.el8.x86_64 radcli-1.2.11-3.el8.x86_64 rrdtool-1.7.0-16.el8.x86_64 sqlite-libs-3.26.0-3.el8.x86_64 sssd-client-2.2.0-19.el8.x86_64 systemd-libs-239-18.el8_1.1.x86_64 xz-libs-5.2.4-3.el8.x86_64 zeromq-4.3.2-1.el8.x86_64 zlib-1.2.11-10.el8.x86_64
(gdb) bt
#0  0x00007f7604c51101 in free () from /lib64/libc.so.6
#1  0x00000000004d1ff5 in nDPIStats::~nDPIStats (this=0x7f7014c42410, __in_chrg=<optimized out>) at src/nDPIStats.cpp:65
#2  0x00000000004418ef in GenericTrafficElement::~GenericTrafficElement (this=0x7f6fa8a25550, __in_chrg=<optimized out>) at /home/deri/ntopng/include/GenericTrafficElement.h:50
#3  0x0000000000441aaa in TimeseriesStats::~TimeseriesStats (this=0x7f6fa8a25550, __in_chrg=<optimized out>) at /home/deri/ntopng/include/TimeseriesStats.h:59
#4  0x0000000000441ac6 in TimeseriesStats::~TimeseriesStats (this=0x7f6fa8a25550, __in_chrg=<optimized out>) at /home/deri/ntopng/include/TimeseriesStats.h:59
#5  0x00000000004c5a8b in HostTimeseriesPoint::~HostTimeseriesPoint (this=0x7f6fa8a254c0, __in_chrg=<optimized out>) at src/HostTimeseriesPoint.cpp:51
#6  0x00000000004c5b04 in HostTimeseriesPoint::~HostTimeseriesPoint (this=0x7f6fa8a254c0, __in_chrg=<optimized out>) at src/HostTimeseriesPoint.cpp:54
#7  0x0000000000521506 in LocalHost::~LocalHost (this=0x7f6f19a69ff0, __in_chrg=<optimized out>) at src/LocalHost.cpp:43
#8  0x000000000052158a in LocalHost::~LocalHost (this=0x7f6f19a69ff0, __in_chrg=<optimized out>) at src/LocalHost.cpp:45
#9  0x00000000004e5e91 in GenericHash::walkAllStates (this=0x45e93f10, walker=0x4f66f0 <NetworkInterface::generic_periodic_hash_entry_state_update(GenericHashEntry*, void*)>, user_data=0x7f758a0d1330)
    at src/GenericHash.cpp:140
#10 0x00000000004f690c in NetworkInterface::periodicHTStateUpdate (this=0x2c8dca0, deadline=1580964705, vm=0x7f7571c8b208, skip_user_scripts=false) at src/NetworkInterface.cpp:2730
#11 0x00000000004ab154 in ntop_periodic_ht_state_update (vm=0x7f7571c8b208) at src/LuaEngine.cpp:6184
#12 0x00000000005af237 in luaD_precall.part.3 ()
#13 0x00000000005ba0a5 in luaV_execute ()
#14 0x00000000005af488 in luaD_call ()
#15 0x00000000005af4b1 in luaD_callnoyield ()
#16 0x00000000005ae90c in luaD_rawrunprotected ()
#17 0x00000000005af7bb in luaD_pcall ()
#18 0x00000000005ace14 in lua_pcallk ()
#19 0x00000000004b9d03 in LuaEngine::run_loaded_script (this=0x7f7550759990) at src/LuaEngine.cpp:11990
#20 0x0000000000415f16 in ThreadedActivity::runScript (this=0x4fb58360, script_path=0x7f74f0001180 "/usr/share/ntopng/scripts/callbacks/interface/ht_state_update.lua", iface=0x2c8dca0, deadline=1580964705)
    at src/ThreadedActivity.cpp:238
#21 0x00000000004e1712 in ThreadPool::run (this=0x4fb708d0) at src/ThreadPool.cpp:102
#22 0x00000000004e13ad in doRun (ptr=0x4fb708d0) at src/ThreadPool.cpp:31
#23 0x00007f7606fa52de in start_thread () from /lib64/libpthread.so.0
#24 0x00007f7604cc74b3 in clone () from /lib64/libc.so.6
 
core-ht_state_update-sig6-user992-group988-pid25341-time1580957982
 
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f43a925199f in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f4330878700 (LWP 31201))]
Missing separate debuginfos, use: yum debuginfo-install brotli-1.0.6-1.el8.x86_64 bzip2-libs-1.0.6-26.el8.x86_64 cairo-1.15.12-3.el8.x86_64 cyrus-sasl-lib-2.1.27-1.el8.x86_64 expat-2.2.5-3.el8.x86_64 fontconfig-2.13.1-3.el8.x86_64 freetype-2.9.1-4.el8.x86_64 fribidi-1.0.4-7.el8_1.x86_64 glib2-2.56.4-7.el8.x86_64 glibc-2.28-72.el8.x86_64 gmp-6.1.2-10.el8.x86_64 gnutls-3.6.8-8.el8.x86_64 harfbuzz-1.7.5-3.el8.x86_64 hiredis-0.13.3-11.el8.x86_64 json-c-0.13.1-0.2.el8.x86_64 keyutils-libs-1.5.10-6.el8.x86_64 krb5-libs-1.17-9.el8.x86_64 libX11-1.6.7-1.el8.x86_64 libXau-1.0.8-13.el8.x86_64 libXext-1.3.3-9.el8.x86_64 libXrender-0.9.10-7.el8.x86_64 libblkid-2.32.1-17.el8.x86_64 libcap-2.26-1.el8.x86_64 libcom_err-1.44.6-3.el8.x86_64 libcurl-7.61.1-11.el8.x86_64 libdatrie-0.2.9-7.el8.x86_64 libffi-3.1-21.el8.x86_64 libgcc-8.3.1-4.5.el8.x86_64 libidn2-2.2.0-1.el8.x86_64 libmaxminddb-1.2.0-6.el8.x86_64 libnghttp2-1.33.0-1.el8_0.1.x86_64 libpng-1.6.34-5.el8.x86_64 libpsl-0.20.2-5.el8.x86_64 libselinux-2.9-2.1.el8.x86_64 libsodium-1.0.18-2.el8.x86_64 libssh-0.9.0-4.el8.x86_64 libstdc++-8.3.1-4.5.el8.x86_64 libtasn1-4.13-3.el8.x86_64 libthai-0.1.27-2.el8.x86_64 libunistring-0.9.9-3.el8.x86_64 libunwind-1.3.1-3.el8.x86_64 libxcb-1.13-5.el8.x86_64 libxcrypt-4.1.1-4.el8.x86_64 libxml2-2.9.7-5.el8.x86_64 libzstd-1.4.4-1.el8.x86_64 mysql-libs-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 nettle-3.4.1-1.el8.x86_64 openldap-2.4.46-10.el8.x86_64 openpgm-5.2.122-21.el8.x86_64 openssl-libs-1.1.1c-2.el8.x86_64 p11-kit-0.23.14-5.el8_0.x86_64 pango-1.42.4-6.el8.x86_64 pcre-8.42-4.el8.x86_64 pcre2-10.32-1.el8.x86_64 pixman-0.36.0-1.el8.x86_64 radcli-1.2.11-3.el8.x86_64 rrdtool-1.7.0-16.el8.x86_64 sqlite-libs-3.26.0-3.el8.x86_64 sssd-client-2.2.0-19.el8.x86_64 systemd-libs-239-18.el8_1.1.x86_64 xz-libs-5.2.4-3.el8.x86_64 zeromq-4.3.2-1.el8.x86_64 zlib-1.2.11-10.el8.x86_64
(gdb) bt
#0  0x00007f43a925199f in raise () from /lib64/libc.so.6
#1  0x00007f43a923bcf5 in abort () from /lib64/libc.so.6
#2  0x00007f43a9294dd7 in __libc_message () from /lib64/libc.so.6
#3  0x00007f43a929b70c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f43a929d0e8 in _int_free () from /lib64/libc.so.6
#5  0x00000000004d1ff5 in nDPIStats::~nDPIStats (this=0x7f34d58eaca0, __in_chrg=<optimized out>) at src/nDPIStats.cpp:65
#6  0x00000000004418ef in GenericTrafficElement::~GenericTrafficElement (this=0x7f34d58ea4c0, __in_chrg=<optimized out>) at /home/deri/ntopng/include/GenericTrafficElement.h:50
#7  0x0000000000441aaa in TimeseriesStats::~TimeseriesStats (this=0x7f34d58ea4c0, __in_chrg=<optimized out>) at /home/deri/ntopng/include/TimeseriesStats.h:59
#8  0x0000000000440ec0 in HostStats::~HostStats (this=0x7f34d58ea4c0, __in_chrg=<optimized out>) at src/HostStats.cpp:45
#9  0x00000000004937cf in LocalHostStats::~LocalHostStats (this=0x7f34d58ea4c0, __in_chrg=<optimized out>) at src/LocalHostStats.cpp:42
#10 0x00000000004937f0 in LocalHostStats::~LocalHostStats (this=0x7f34d58ea4c0, __in_chrg=<optimized out>) at src/LocalHostStats.cpp:49
#11 0x000000000043302b in Host::~Host (this=0x7f34d58e9e40, __in_chrg=<optimized out>) at src/Host.cpp:83
#12 0x0000000000521566 in LocalHost::~LocalHost (this=0x7f34d58e9e40, __in_chrg=<optimized out>) at src/LocalHost.cpp:42
#13 0x000000000052158a in LocalHost::~LocalHost (this=0x7f34d58e9e40, __in_chrg=<optimized out>) at src/LocalHost.cpp:45
#14 0x00000000004e5e91 in GenericHash::walkAllStates (this=0x3e668450, walker=0x4f66f0 <NetworkInterface::generic_periodic_hash_entry_state_update(GenericHashEntry*, void*)>, user_data=0x7f4330877330)
    at src/GenericHash.cpp:140
#15 0x00000000004f690c in NetworkInterface::periodicHTStateUpdate (this=0x23ffcc0, deadline=1580957985, vm=0x7f4314bc9ba8, skip_user_scripts=false) at src/NetworkInterface.cpp:2730
#16 0x00000000004ab154 in ntop_periodic_ht_state_update (vm=0x7f4314bc9ba8) at src/LuaEngine.cpp:6184
#17 0x00000000005af237 in luaD_precall.part.3 ()
#18 0x00000000005ba0a5 in luaV_execute ()
#19 0x00000000005af488 in luaD_call ()
#20 0x00000000005af4b1 in luaD_callnoyield ()
#21 0x00000000005ae90c in luaD_rawrunprotected ()
#22 0x00000000005af7bb in luaD_pcall ()
#23 0x00000000005ace14 in lua_pcallk ()
#24 0x00000000004b9d03 in LuaEngine::run_loaded_script (this=0x7f42f84a8d90) at src/LuaEngine.cpp:11990
#25 0x0000000000415f16 in ThreadedActivity::runScript (this=0x4e885960, script_path=0x7f4294001000 "/usr/share/ntopng/scripts/callbacks/interface/ht_state_update.lua", iface=0x23ffcc0, deadline=1580957985)
    at src/ThreadedActivity.cpp:238
#26 0x00000000004e1712 in ThreadPool::run (this=0x4e5e97a0) at src/ThreadPool.cpp:102
#27 0x00000000004e13ad in doRun (ptr=0x4e5e97a0) at src/ThreadPool.cpp:31
#28 0x00007f43ab5f42de in start_thread () from /lib64/libpthread.so.0
#29 0x00007f43a93164b3 in clone () from /lib64/libc.so.6
```

**Comment by simonemainardi** [comment]
config is

```
-G=/var/run/ntopng.pid
 
-i=tcp://10.157.97.90:5555c
-i=tcp://10.157.97.90:5556c
-i=tcp://10.157.97.90:5557c
-i=tcp://10.157.97.90:5558c
-i=tcp://10.157.97.90:5559c
-i=tcp://10.157.97.90:5560c
-i=tcp://10.157.97.90:5561c
-i=tcp://10.157.97.90:5562c
-i=tcp://10.157.97.90:5563c
-i=tcp://10.157.97.90:5564c
-i=tcp://10.157.97.90:5565c
-i=tcp://10.157.97.90:5566c
 
-i=view:tcp://10.157.97.90:5555c,tcp://10.157.97.90:5556c,tcp://10.157.97.90:5557c,tcp://10.157.97.90
:5558c,tcp://10.157.97.90:5559c,tcp://10.157.97.90:5560c,tcp://10.157.97.90:5561c,tcp://10.157.97.90:
5562c,tcp://10.157.97.90:5563c,tcp://10.157.97.90:5564c,tcp://10.157.97.90:5565c,tcp://10.157.97.90:5
566c
 
--max-num-flows=5000000
--max-num-hosts=2000000
```

**Comment by emanuele-f** [comment]
The crash cannot be reproduced. Tested with 8 ZC cento instances sending traffic via zmq to a remote ntopng with a view which aggregates the 8 zmq interfaces. Tested with approximately 400k hosts and 5M flows.

**Comment by simonemainardi** [comment]
Closing for inactivity. Will reopen if necessary.
