### ISSUE TITLE
minute.lua and hour.lua deadlock on StatsManager::openStore mutex

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3511]
Scripts above have been found to be blocked for hours. The relevant part of the stacktrace is the following 

```
Thread 12 (Thread 0x7ffae6673700 (LWP 32453)):
#0  0x00007ffb0c27510d in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffb0c26e023 in __GI___pthread_mutex_lock (mutex=0x55a5385b3148) at ../nptl/pthread_mutex_lock.c:78
#2  0x000055a528879630 in Mutex::lock(char const*, int, bool) (this=0x55a5385b3148, filename=0x55a528a103cb "src/StatsManager.cpp", line=76, trace_errors=true) at src/Mutex.cpp:43
#3  0x000055a5288353a2 in StatsManager::openStore(char const*) (this=0x55a5385b3130, cache_name=0x55a528a10363 "MINUTE_STATS") at src/StatsManager.cpp:76
#4  0x000055a5288359af in StatsManager::retrieveStatsInterval(statsManagerRetrieval*, char const*, long, long) (this=0x55a5385b3130, retvals=0x7ffae6672360, cache_name=0x55a528a10363 "MINUTE_STATS", key_start=1583305200, key_end=1583308800) at src/StatsManager.cpp:222
#5  0x000055a528835b3b in StatsManager::retrieveMinuteStatsInterval(long, long, statsManagerRetrieval*) (this=0x55a5385b3130, epoch_start=1583305200, epoch_end=1583308800, retvals=0x7ffae6672360) at src/StatsManager.cpp:261
#6  0x000055a52880cd4f in ntop_stats_get_samplings_of_minutes_from_epoch(lua_State*) (vm=0x7ffad0e0cdc8) at src/LuaEngine.cpp:7817
#7  0x000055a528900b66 in luaD_precall ()
#8  0x000055a52890c2ed in luaV_execute ()
#9  0x000055a528900e3f in luaD_call ()
#10 0x000055a528900e91 in luaD_callnoyield ()
#11 0x000055a5288fe46c in lua_callk ()
#12 0x000055a52891e55c in ll_require ()
#13 0x000055a528900b66 in luaD_precall ()
#14 0x000055a52890c2ed in luaV_execute ()
#15 0x000055a528900e3f in luaD_call ()
#16 0x000055a528900e91 in luaD_callnoyield ()
#17 0x000055a5289002b2 in luaD_rawrunprotected ()
#18 0x000055a52890118b in luaD_pcall ()
#19 0x000055a5288fe534 in lua_pcallk ()
---Type <return> to continue, or q <return> to quit---
#20 0x000055a52881848c in LuaEngine::run_loaded_script() (this=0x7ffad07d18d0) at src/LuaEngine.cpp:12133
#21 0x000055a5287d587b in ThreadedActivity::runScript(char*, NetworkInterface*, long) (this=0x55a538decb30, script_path=0x7ffaa4000f70 "/usr/share/ntopng/scripts/callbacks/interface/hourly.lua", iface=0x55a52adf77e0, deadline=1583312400)
    at src/ThreadedActivity.cpp:413
#22 0x000055a52884f02f in ThreadPool::run() (this=0x55a538d480e0) at src/ThreadPool.cpp:103
#23 0x000055a52884ec77 in doRun(void*) (ptr=0x55a538d480e0) at src/ThreadPool.cpp:31
#24 0x00007ffb0c26b6db in start_thread (arg=0x7ffae6673700) at pthread_create.c:463
#25 0x00007ffb09b6488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7ffae5671700 (LWP 32455)):
#0  0x00007ffb0c27510d in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffb0c26e023 in __GI___pthread_mutex_lock (mutex=0x55a5385b3148) at ../nptl/pthread_mutex_lock.c:78
#2  0x000055a528879630 in Mutex::lock(char const*, int, bool) (this=0x55a5385b3148, filename=0x55a528a103cb "src/StatsManager.cpp", line=76, trace_errors=true) at src/Mutex.cpp:43
#3  0x000055a5288353a2 in StatsManager::openStore(char const*) (this=0x55a5385b3130, cache_name=0x55a528a10363 "MINUTE_STATS") at src/StatsManager.cpp:76
#4  0x000055a528835c54 in StatsManager::insertSampling(char const*, char const*, long) (this=0x55a5385b3130, sampling=0x7ffac86334b8 "{\"vlan\":[{\"networks\":[{\"senders\":[],\"receivers\":[]}],\"asn\":[{\"senders\":[],\"receivers\":[]}],\"non-local os\":[{\"senders\":[],\"receivers\":[]}],\"address\":\"0\",\"local os\":[{\"senders\":[],\"receivers\":[]}],\"host"..., cache_name=0x55a528a10363 "MINUTE_STATS", key=1583306041) at src/StatsManager.cpp:328
#5  0x000055a528835e6a in StatsManager::insertMinuteSampling(long, char const*) (this=0x55a5385b3130, epoch=1583306041, sampling=0x7ffac86334b8 "{\"vlan\":[{\"networks\":[{\"senders\":[],\"receivers\":[]}],\"asn\":[{\"senders\":[],\"receivers\":[]}],\"non-local os\":[{\"senders\":[],\"receivers\":[]}],\"address\":\"0\",\"local os\":[{\"senders\":[],\"receivers\":[]}],\"host"...) at src/StatsManager.cpp:372
#6  0x000055a52880bd70 in ntop_stats_insert_minute_sampling(lua_State*) (vm=0x7ffac8eca2a8) at src/LuaEngine.cpp:7474
#7  0x000055a528900b66 in luaD_precall ()
#8  0x000055a52890c2ed in luaV_execute ()
#9  0x000055a528900e3f in luaD_call ()
#10 0x000055a528900e91 in luaD_callnoyield ()
#11 0x000055a5289002b2 in luaD_rawrunprotected ()
#12 0x000055a52890118b in luaD_pcall ()
#13 0x000055a5288fe534 in lua_pcallk ()
#14 0x000055a52881848c in LuaEngine::run_loaded_script() (this=0x7ffac8b0be80) at src/LuaEngine.cpp:12133
#15 0x000055a5287d587b in ThreadedActivity::runScript(char*, NetworkInterface*, long) (this=0x55a538947570, script_path=0x7ffa98000f70 "/usr/share/ntopng/scripts/callbacks/interface/minute.lua", iface=0x55a52adf77e0, deadline=1583306100)
    at src/ThreadedActivity.cpp:413
#16 0x000055a52884f02f in ThreadPool::run() (this=0x55a538cc8080) at src/ThreadPool.cpp:103
---Type <return> to continue, or q <return> to quit---
#17 0x000055a52884ec77 in doRun(void*) (ptr=0x55a538cc8080) at src/ThreadPool.cpp:31
#18 0x00007ffb0c26b6db in start_thread (arg=0x7ffae5671700) at pthread_create.c:463
#19 0x00007ffb09b6488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

other UI-threads blocked are
```
Thread 6 (Thread 0x7ffafc88b700 (LWP 32423)):
#0  0x00007ffb0c27510d in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffb0c26e023 in __GI___pthread_mutex_lock (mutex=0x55a5385b3148) at ../nptl/pthread_mutex_lock.c:78
#2  0x000055a528879630 in Mutex::lock(char const*, int, bool) (this=0x55a5385b3148, filename=0x55a528a103cb "src/StatsManager.cpp", line=233, trace_errors=true) at src/Mutex.cpp:43
#3  0x000055a528835a4c in StatsManager::retrieveStatsInterval(statsManagerRetrieval*, char const*, long, long) (this=0x55a5385b3130, retvals=0x7ffafc8882f0, cache_name=0x55a528a10370 "HOUR_STATS", key_start=1583347680, key_end=1583347680) at src/StatsManager.cpp:233
#4  0x000055a528835b87 in StatsManager::retrieveHourStatsInterval(long, long, statsManagerRetrieval*) (this=0x55a5385b3130, epoch_start=1583347680, epoch_end=1583347680, retvals=0x7ffafc8882f0) at src/StatsManager.cpp:283
#5  0x000055a52880d04d in ntop_stats_get_samplings_of_hours_from_epoch(lua_State*) (vm=0x7ffae84dad18) at src/LuaEngine.cpp:7871
#6  0x000055a528900b66 in luaD_precall ()
#7  0x000055a52890c2ed in luaV_execute ()
#8  0x000055a528900e3f in luaD_call ()
#9  0x000055a528900e91 in luaD_callnoyield ()
#10 0x000055a5289002b2 in luaD_rawrunprotected ()
#11 0x000055a52890118b in luaD_pcall ()
#12 0x000055a5288fe534 in lua_pcallk ()
#13 0x000055a5288b2f75 in LuaHandler::luaL_dofileM(bool) (this=0x7ffae84c7a50, execute=true) at pro/LuaHandler.cpp:32
#14 0x000055a528816df1 in __ntop_lua_handlefile(lua_State*, char*, bool) (L=0x7ffae84dad18, script_path=0x7ffafc888d50 "/usr/share/ntopng/scripts/lua/pro/get_ts_table.lua", ex=true) at src/LuaEngine.cpp:11015
#15 0x000055a528819cf5 in LuaEngine::handle_script_request(mg_connection*, mg_request_info const*, char*, bool*, char const*, char const*, bool) (this=0x7ffae84dab60, conn=0x7ffae8000b20, request_info=0x7ffae8000b20, script_path=0x7ffafc888d50 "/usr/share/ntopng/scripts/lua/pro/get_ts_table.lua", attack_attempt=0x7ffafc888c10, user=0x7ffafc888cf0 "remote", group=0x7ffafc888d20 "administrator", localuser=true) at src/LuaEngine.cpp:12633
#16 0x000055a5287d2d6a in handle_lua_request(mg_connection*) (conn=0x7ffae8000b20) at src/HTTPserver.cpp:1009
#17 0x000055a5287cc1aa in handle_request(mg_connection*) (conn=0x7ffae8000b20) at src/../third-party/mongoose/mongoose.c:4430
#18 0x000055a5287ce578 in process_new_connection(mg_connection*) (conn=0x7ffae8000b20) at src/../third-party/mongoose/mongoose.c:5156
#19 0x000055a5287ceaf8 in worker_thread(void*) (thread_func_param=0x55a52ae9b200) at src/../third-party/mongoose/mongoose.c:5250
#20 0x00007ffb0c26b6db in start_thread (arg=0x7ffafc88b700) at pthread_create.c:463
#21 0x00007ffb09b6488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ffafd08c700 (LWP 32422)):
#0  0x00007ffb0c27510d in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffb0c26e023 in __GI___pthread_mutex_lock (mutex=0x55a5385b3148) at ../nptl/pthread_mutex_lock.c:78
---Type <return> to continue, or q <return> to quit---
#2  0x000055a528879630 in Mutex::lock(char const*, int, bool) (this=0x55a5385b3148, filename=0x55a528a103cb "src/StatsManager.cpp", line=233, trace_errors=true) at src/Mutex.cpp:43
#3  0x000055a528835a4c in StatsManager::retrieveStatsInterval(statsManagerRetrieval*, char const*, long, long) (this=0x55a5385b3130, retvals=0x7ffafd0892f0, cache_name=0x55a528a10370 "HOUR_STATS", key_start=1583347800, key_end=1583347800) at src/StatsManager.cpp:233
#4  0x000055a528835b87 in StatsManager::retrieveHourStatsInterval(long, long, statsManagerRetrieval*) (this=0x55a5385b3130, epoch_start=1583347800, epoch_end=1583347800, retvals=0x7ffafd0892f0) at src/StatsManager.cpp:283
#5  0x000055a52880d04d in ntop_stats_get_samplings_of_hours_from_epoch(lua_State*) (vm=0x7ffaf4095c68) at src/LuaEngine.cpp:7871
#6  0x000055a528900b66 in luaD_precall ()
#7  0x000055a52890c2ed in luaV_execute ()
#8  0x000055a528900e3f in luaD_call ()
#9  0x000055a528900e91 in luaD_callnoyield ()
#10 0x000055a5289002b2 in luaD_rawrunprotected ()
#11 0x000055a52890118b in luaD_pcall ()
#12 0x000055a5288fe534 in lua_pcallk ()
#13 0x000055a5288b2f75 in LuaHandler::luaL_dofileM(bool) (this=0x7ffaf402b240, execute=true) at pro/LuaHandler.cpp:32
#14 0x000055a528816df1 in __ntop_lua_handlefile(lua_State*, char*, bool) (L=0x7ffaf4095c68, script_path=0x7ffafd089d50 "/usr/share/ntopng/scripts/lua/pro/get_ts_table.lua", ex=true) at src/LuaEngine.cpp:11015
```

The only guy who seems to be holding the lock is the `daily.lua`

```
Thread 13 (Thread 0x7ffae5e72700 (LWP 32454)):
#0  0x00007ffb09b527c3 in __GI___fxstat (vers=<optimized out>, fd=22, buf=0x7ffae5e70620) at ../sysdeps/unix/sysv/linux/wordsize-64/fxstat.c:35
#1  0x00007ffb0ca657ee in  () at /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#2  0x00007ffb0ca4da5b in  () at /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#3  0x00007ffb0caa4ad6 in  () at /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#4  0x00007ffb0caa54a2 in  () at /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#5  0x00007ffb0cacdcbe in  () at /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#6  0x00007ffb0cad33e1 in sqlite3_step () at /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#7  0x000055a528835d69 in StatsManager::insertSampling(char const*, char const*, long) (this=0x55a5385b3130, sampling=0x7ffac4b5c4a8 "{\"vlan\":[{\"hosts\":[{\"senders\":[{\"local\":\"false\",\"value\":\"2347203926961\",\"address\":\"Other\"},{\"local\":\"false\",\"value\":\"54375226556\",\"label\":\"\",\"address\":\"157.240.193.10\"},{\"local\":\"false\",\"value\":\"43127"..., cache_name=0x55a528a1037b "DAY_STATS", key=1583305980) at src/StatsManager.cpp:342
#8  0x000055a528835eea in StatsManager::insertDaySampling(long, char const*) (this=0x55a5385b3130, epoch=1583305980, sampling=0x7ffac4b5c4a8 "{\"vlan\":[{\"hosts\":[{\"senders\":[{\"local\":\"false\",\"value\":\"2347203926961\",\"address\":\"Other\"},{\"local\":\"false\",\"value\":\"54375226556\",\"label\":\"\",\"address\":\"157.240.193.10\"},{\"local\":\"false\",\"value\":\"43127"...) at src/StatsManager.cpp:406
#9  0x000055a52880c17c in ntop_stats_insert_day_sampling(lua_State*) (vm=0x7ffac4000d78) at src/LuaEngine.cpp:7556
#10 0x000055a528900b66 in luaD_precall ()
#11 0x000055a52890c2ed in luaV_execute ()
#12 0x000055a528900e3f in luaD_call ()
#13 0x000055a528900e91 in luaD_callnoyield ()
#14 0x000055a5288fe46c in lua_callk ()
#15 0x000055a52891e55c in ll_require ()
#16 0x000055a528900b66 in luaD_precall ()
#17 0x000055a52890c2ed in luaV_execute ()
#18 0x000055a528900e3f in luaD_call ()
#19 0x000055a528900e91 in luaD_callnoyield ()
#20 0x000055a5289002b2 in luaD_rawrunprotected ()
#21 0x000055a52890118b in luaD_pcall ()
#22 0x000055a5288fe534 in lua_pcallk ()
#23 0x000055a52881848c in LuaEngine::run_loaded_script() (this=0x7ffac4000d50) at src/LuaEngine.cpp:12133
#24 0x000055a5287d587b in ThreadedActivity::runScript(char*, NetworkInterface*, long) (this=0x55a5388dfb40, script_path=0x7ffa90000f70 "/usr/share/ntopng/scripts/callbacks/interface/daily.lua", iface=0x55a52adf77e0, deadline=1583366400)
    at src/ThreadedActivity.cpp:413
#25 0x000055a52884f02f in ThreadPool::run() (this=0x55a538cc8080) at src/ThreadPool.cpp:103
#26 0x000055a52884ec77 in doRun(void*) (ptr=0x55a538cc8080) at src/ThreadPool.cpp:31
#27 0x00007ffb0c26b6db in start_thread (arg=0x7ffae5e72700) at pthread_create.c:463
#28 0x00007ffb09b6488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by simonemainardi** [comment]
Found this during the investigation.

Seems daily.lua is blocked on the very same query as printing multiple backtraces always yield the same function call with the same parameters (same query). 

Seems this while is not returning:
```
, cache_name=0x55decfd2371b "DAY_STATS", key=1583391360) at src/StatsManager.cpp:342
342	  while((rc = sqlite3_step(stmt)) != SQLITE_DONE) {
(gdb) f 6
```

**Comment by simonemainardi** [comment]
return code is 19

```
342	  while((rc = sqlite3_step(stmt)) != SQLITE_DONE) {
(gdb) p rc
$1 = 19
```

**Comment by simonemainardi** [comment]
19 is constraint violation:

```
#define SQLITE_CONSTRAINT  19   /* Abort due to constraint violation */
```

**Comment by simonemainardi** [comment]
confirmed this is a primary key violation.

script is attempting to insert 
```
(gdb) p query
$4 = "INSERT INTO DAY_STATS (TSTAMP, STATS) VALUES(?,?)\000\"value\":\"3278330\",\"label\":\"\",\"local\":\"true\",\"address\":\"10.200.0.150\"},{\"value\":\"2832160\",\"label\":\"\",\"local\":\"false\",\"address\":\"31.13.86.51\"},{\"value\":"...
(gdb) p key
$5 = 1583391360
```

However, an entry with primary key TSTAMP already exists in the table:

```
# sqlite3 top_talkers.db
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> select 1 from  DAY_STATS where TSTAMP=1583391360 limit 1;
1
```

Looking at the timestamp value which ntopng is trying to insert, it is equal to the ntopng start time:

```
# date -d @1583391360
Thu Mar  5 06:56:00 UTC 2020
# ps -eo  pid,lstart,cmd | grep ntopng
 8044 Thu Mar  5 06:56:45 2020 /usr/local/bin/ntopng /run/ntopng.conf
```

so day is not supposed to do that action at that time
