### ISSUE TITLE
ntopng crashes frequently

### ISSUE THREAD

**Issue by bipin-stcs** [ntop/ntopng#3562]
Hi,
ntopng crashes frequently. 

```
v.3.9.200304	[Enterprise/Professional build]
GIT rev:	dev:8865cacb98f035369ecf25236f64ca8c275090d2:20200304
Pro rev:	r2746
Built on:	Ubuntu 16.04.6 LTS
System Id:	XXXXXXXX
Platform:	x86_64
Edition:	Enterprise
License Type:	Permanent
```

Attachment

1.  stack trace
```

#0  0x00007ffff3fd4746 in strlen () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4649264 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000000000041d59d in AlertableEntity::setEntityValue (this=0x7fff7400a570, ent_val=0x0) at /home/deri/ntopng/include/AlertableEntity.h:79
#3  0x0000000000520ddf in NetworkStats::NetworkStats (this=0x7fff7400a570, iface=0xe3c390, _network_id=0 '\000') at src/NetworkStats.cpp:31
#4  0x000000000044c3de in Country::Country (this=0x7fff7400a360, _iface=0xe3c390, country=0x7fff7bffe1a0 "OM") at src/Country.cpp:26
#5  0x0000000000481ebe in NetworkInterface::getCountry (this=0xe3c390, country_name=0x7fff7bffe1a0 "OM", create_if_not_present=true, is_inline_call=true) at src/NetworkInterface.cpp:5509
#6  0x0000000000418f71 in Host::initialize (this=0x7fff740097c0, _mac=0x7fff74009020, _vlanId=0, init_all=true) at src/Host.cpp:210
#7  0x00000000004183ce in Host::Host (this=0x7fff740097c0, _iface=0xe3c390, _mac=0x7fff74009020, _vlanId=0, _ip=0x7fff7bffe5c0) at src/Host.cpp:45
#8  0x00000000004a5d56 in RemoteHost::RemoteHost (this=0x7fff740097c0, _iface=0xe3c390, _mac=0x7fff74009020, _vlanId=0, _ip=0x7fff7bffe5c0) at src/RemoteHost.cpp:26
#9  0x0000000000477070 in NetworkInterface::findFlowHosts (this=0xe3c390, vlanId=0, src_mac=0x7fff74009020, _src_ip=0x7fff7bffe5c0, src=0x7fff740093c8, dst_mac=0x7fff74009020, 
    _dst_ip=0x7fff7bffe5e0, dst=0x7fff740093d0) at src/NetworkInterface.cpp:2411
#10 0x00000000004513f4 in Flow::Flow (this=0x7fff74009380, _iface=0xe3c390, _vlanId=0, _protocol=17 '\021', _cli_mac=0x7fff74009020, _cli_ip=0x7fff7bffe5c0, _cli_port=6505, 
    _srv_mac=0x7fff74009020, _srv_ip=0x7fff7bffe5e0, _srv_port=26690, _icmp_info=0x0, _first_seen=1584260640, _last_seen=1584260725) at src/Flow.cpp:92
#11 0x000000000047120f in NetworkInterface::getFlow (this=0xe3c390, srcMac=0x7fff74009020, dstMac=0x7fff74009020, vlan_id=0, deviceIP=183232586, inIndex=29, outIndex=48, icmp_info=0x0, 
    src_ip=0x7fff7bffe5c0, dst_ip=0x7fff7bffe5e0, src_port=6505, dst_port=26690, l4_proto=17 '\021', src2dst_direction=0x7fff7bffe511, first_seen=1584260640, last_seen=1584260725, 
    len_on_wire=0, new_flow=0x7fff7bffe514, create_if_missing=true) at src/NetworkInterface.cpp:867
#12 0x00000000004a6f36 in ParserInterface::processFlow (this=0xe3c390, zflow=0x7fff7bffe770) at src/ParserInterface.cpp:160
#13 0x00000000004ec75d in ZMQParserInterface::preprocessFlow (this=0xe3c390, flow=0x7fff7bffe770) at src/ZMQParserInterface.cpp:1041
#14 0x00000000004ed5d8 in ZMQParserInterface::parseSingleTLVFlow (this=0xe3c390, deserializer=0x7fff7bffea40, source_id=0 '\000') at src/ZMQParserInterface.cpp:1377
#15 0x00000000004ed8e1 in ZMQParserInterface::parseTLVFlow (this=0xe3c390, payload=0x7fff740008e0 "\001\001+\b", payload_size=137, source_id=0 '\000', data=0xe3c390)
    at src/ZMQParserInterface.cpp:1457
#16 0x0000000000499833 in ZMQCollectorInterface::collect_flows (this=0xe3c390) at src/ZMQCollectorInterface.cpp:421
#17 0x0000000000499a6a in packetPollLoop (ptr=0xe3c390) at src/ZMQCollectorInterface.cpp:469
#18 0x00007ffff65bd6ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007ffff405041d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
2.  configuration file
```
-x=512000
-X=512000
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:5556
-w=3000
-m="IP-ADDRESS"
-n=3
-S=local
-q=
-F=es;ntopng;ntopng-%Y.%m.%d;http://IP-ADDRESS:9200/_bulk;
-max-num-flows=1000000
```

Regards
Bipin

**Comment by bipin-stcs** [comment]
```

#0  0x00007ffff3fd4746 in strlen () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4649264 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000000000041d59d in AlertableEntity::setEntityValue (this=0x7fff7400a570, ent_val=0x0) at /home/deri/ntopng/include/AlertableEntity.h:79
#3  0x0000000000520ddf in NetworkStats::NetworkStats (this=0x7fff7400a570, iface=0xe3c390, _network_id=0 '\000') at src/NetworkStats.cpp:31
#4  0x000000000044c3de in Country::Country (this=0x7fff7400a360, _iface=0xe3c390, country=0x7fff7bffe1a0 "OM") at src/Country.cpp:26
#5  0x0000000000481ebe in NetworkInterface::getCountry (this=0xe3c390, country_name=0x7fff7bffe1a0 "OM", create_if_not_present=true, is_inline_call=true) at src/NetworkInterface.cpp:5509
#6  0x0000000000418f71 in Host::initialize (this=0x7fff740097c0, _mac=0x7fff74009020, _vlanId=0, init_all=true) at src/Host.cpp:210
#7  0x00000000004183ce in Host::Host (this=0x7fff740097c0, _iface=0xe3c390, _mac=0x7fff74009020, _vlanId=0, _ip=0x7fff7bffe5c0) at src/Host.cpp:45
#8  0x00000000004a5d56 in RemoteHost::RemoteHost (this=0x7fff740097c0, _iface=0xe3c390, _mac=0x7fff74009020, _vlanId=0, _ip=0x7fff7bffe5c0) at src/RemoteHost.cpp:26
#9  0x0000000000477070 in NetworkInterface::findFlowHosts (this=0xe3c390, vlanId=0, src_mac=0x7fff74009020, _src_ip=0x7fff7bffe5c0, src=0x7fff740093c8, dst_mac=0x7fff74009020, 
    _dst_ip=0x7fff7bffe5e0, dst=0x7fff740093d0) at src/NetworkInterface.cpp:2411
#10 0x00000000004513f4 in Flow::Flow (this=0x7fff74009380, _iface=0xe3c390, _vlanId=0, _protocol=17 '\021', _cli_mac=0x7fff74009020, _cli_ip=0x7fff7bffe5c0, _cli_port=6505, 
    _srv_mac=0x7fff74009020, _srv_ip=0x7fff7bffe5e0, _srv_port=26690, _icmp_info=0x0, _first_seen=1584260640, _last_seen=1584260725) at src/Flow.cpp:92
#11 0x000000000047120f in NetworkInterface::getFlow (this=0xe3c390, srcMac=0x7fff74009020, dstMac=0x7fff74009020, vlan_id=0, deviceIP=183232586, inIndex=29, outIndex=48, icmp_info=0x0, 
    src_ip=0x7fff7bffe5c0, dst_ip=0x7fff7bffe5e0, src_port=6505, dst_port=26690, l4_proto=17 '\021', src2dst_direction=0x7fff7bffe511, first_seen=1584260640, last_seen=1584260725, 
    len_on_wire=0, new_flow=0x7fff7bffe514, create_if_missing=true) at src/NetworkInterface.cpp:867
#12 0x00000000004a6f36 in ParserInterface::processFlow (this=0xe3c390, zflow=0x7fff7bffe770) at src/ParserInterface.cpp:160
#13 0x00000000004ec75d in ZMQParserInterface::preprocessFlow (this=0xe3c390, flow=0x7fff7bffe770) at src/ZMQParserInterface.cpp:1041
#14 0x00000000004ed5d8 in ZMQParserInterface::parseSingleTLVFlow (this=0xe3c390, deserializer=0x7fff7bffea40, source_id=0 '\000') at src/ZMQParserInterface.cpp:1377
#15 0x00000000004ed8e1 in ZMQParserInterface::parseTLVFlow (this=0xe3c390, payload=0x7fff740008e0 "\001\001+\b", payload_size=137, source_id=0 '\000', data=0xe3c390)
    at src/ZMQParserInterface.cpp:1457
#16 0x0000000000499833 in ZMQCollectorInterface::collect_flows (this=0xe3c390) at src/ZMQCollectorInterface.cpp:421
#17 0x0000000000499a6a in packetPollLoop (ptr=0xe3c390) at src/ZMQCollectorInterface.cpp:469
#18 0x00007ffff65bd6ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007ffff405041d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by emanuele-f** [comment]
Should be addressed in 944da5e10b778588d59a973229002b59033c5e64 . The new package will be available in one hour.

**Comment by emanuele-f** [comment]
@bipin-stcs any news? Does the new package work properly?

**Comment by emanuele-f** [comment]
No feedback received. Please reopen if necessary.
