### ISSUE TITLE
nDPIStats::lua crash from 5min.lua

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3704]
```
Thread 18 "5min.lua" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb1ffb700 (LWP 9597)]
0x000055555569f0aa in nDPIStats::lua (this=0x7ffd9de90ba0, iface=0x55555626cea0, vm=0x7ffeb88585b8, with_categories=false, tsLua=false) at src/nDPIStats.cpp:154
154     src/nDPIStats.cpp: No such file or directory.
(gdb)
(gdb)
(gdb)
(gdb) bt
#0  0x000055555569f0aa in nDPIStats::lua (this=0x7ffd9de90ba0, iface=0x55555626cea0, vm=0x7ffeb88585b8, with_categories=false, tsLua=false) at src/nDPIStats.cpp:154
#1  0x00005555556ba8a0 in AutonomousSystem::lua (this=0x7ffdce72bc80, vm=0x7ffeb88585b8, details_level=details_higher, asListElement=false) at src/AutonomousSystem.cpp:103
#2  0x00005555556d4f47 in NetworkInterface::getActiveASList (this=0x55555626cea0, vm=0x7ffeb88585b8, p=0x7ffeb9041f60) at src/NetworkInterface.cpp:6209
#3  0x0000555555663a23 in ntop_get_interface_ases_info (vm=0x7ffeb88585b8) at src/LuaEngine.cpp:1419
#4  0x000055555576be56 in luaD_precall ()
#5  0x00007ffeb86c5100 in ?? ()
#6  0x00007ffeb86c50f0 in ?? ()
#7  0x00007ffeb94d86a0 in ?? ()
#8  0x00007ffeb88585b8 in ?? ()
#9  0x0000000000000001 in ?? ()
#10 0x0000000000000003 in ?? ()
#11 0x00007ffebbfcab20 in ?? ()
#12 0x00005555558aeb9c in ?? ()
#13 0x00007ffeb94d86a0 in ?? ()
#14 0x000055555577762d in luaV_execute ()
#15 0x6d352f6563616672 in ?? ()
#16 0x00007ffeb86c50d0 in ?? ()
#17 0x00007fffa2989600 in ?? ()
#18 0x00007ffebbfcaaf0 in ?? ()
#19 0x00007ffebbfcaaf0 in ?? ()
#20 0x00007ffeb8f337c0 in ?? ()
#21 0x0000000900000000 in ?? ()
#22 0x0000000000000008 in ?? ()
#23 0x0000000000000000 in ?? ()
```

**Comment by simonemainardi** [comment]
User confirms instance has been running for three days and the crash is no longer occurring after the fixes.
