### ISSUE TITLE
Assertion in enqueue

### ISSUE THREAD

**Issue by vimusov** [ntop/ntopng#4816]
ntopng 4.2 fails with assertion in enqueue.

Arguments: `ntopng -s -l 1 -v 6 -i ens4`

Assertion: `/usr/include/c++/10/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = Flow*; _Alloc = std::allocator<Flow*>; std::vector<_Tp, _Alloc>::reference = Flow*&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.`

Backtrace from gdb:
```
Thread 40 "inline ifid 0" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff5f7fe640 (LWP 16322)]
0x00007ffff732bbc5 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff732bbc5 in raise () from /lib64/libc.so.6
#1  0x00007ffff73148a4 in abort () from /lib64/libc.so.6
#2  0x00005555555bf028 in std::__replacement_assert (__file=<optimized out>, __line=<optimized out>, __function=<optimized out>, __condition=<optimized out>) at /usr/include/c++/10/x86_64-redhat-linux/bits/c++config.h:2560
#3  0x0000555555667cef in std::vector<Flow*, std::allocator<Flow*> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/10/bits/stl_vector.h:1045
#4  std::vector<Flow*, std::allocator<Flow*> >::operator[] (this=0x555556196ed0, this=0x555556196ed0, __n=<optimized out>) at /usr/include/c++/10/bits/stl_vector.h:1043
#5  SPSCQueue<Flow*>::enqueue (flush=true, item=0x7fffe4001900, this=0x555556196e40) at /usr/src/debug/ntopng-4.2-1.1607058371.utm.utm.x86_64/include/SPSCQueue.h:116
#6  NetworkInterface::hookEnqueue(long, Flow*) [clone .constprop.0] (this=0x555555d87660, f=0x7fffe4001900, t=<optimized out>) at src/NetworkInterface.cpp:637
#7  0x00005555555d39c0 in GenericHash::purgeIdle (this=0x5555560a2570, tv=0x7fff5f7fd330, force_idle=false) at src/GenericHash.cpp:348
#8  0x00005555556338d4 in NetworkInterface::purgeIdleFlows (force_idle=false, this=0x555555d87660) at src/NetworkInterface.cpp:5165
#9  NetworkInterface::purgeIdle (this=0x555555d87660, when=1607403841, force_idle=<optimized out>) at src/NetworkInterface.cpp:1643
#10 0x00005555556419ad in NetworkInterface::purgeIdle (force_idle=false, when=<optimized out>, this=<optimized out>) at /usr/src/debug/ntopng-4.2-1.1607058371.utm.utm.x86_64/include/NtopGlobals.h:40
#11 NetworkInterface::dissectPacket (ndpiProtocol=<synthetic pointer>, bridge_iface_idx=1, ingressPacket=true, sender_mac=0x0, flow=0x7fff5f7fd448, dstHost=0x7fff5f7fd450, srcHost=0x7fff5f7fd458, packet=0x5555561617e0 "\002\350d\024\324\315\b", h=0x555555babe90, 
    this=<optimized out>) at src/NetworkInterface.cpp:1711
#12 packetPollLoop (ptr=<optimized out>) at src/PcapInterface.cpp:317
#13 0x00007ffff780e3f9 in start_thread () from /lib64/libpthread.so.0
#14 0x00007ffff73efb03 in clone () from /lib64/libc.so.6
```
I suppose it's a bug.

**Comment by vimusov** [comment]
I found a bug and made a patch: #4819

**Comment by simonemainardi** [comment]
Please, comment the PR and explain why it solves. Thanks for your contribution.

**Comment by simonemainardi** [comment]
Confirm. Fixed.
