### ISSUE TITLE
nIndex use causes ntopng crash when working with the test pcap

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5798]
```
Starting program: /home/simone/ntopng/ntopng -i tests/rest/pcap/synscan.pcap -F nindex
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
24/Aug/2021 09:46:17 [Ntop.cpp:2493] Setting local networks to 127.0.0.0/8,fe80::/10
24/Aug/2021 09:46:17 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
24/Aug/2021 09:46:17 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
24/Aug/2021 09:46:17 [NtopPro.cpp:324] [LICENSE] Reading license from /etc/ntopng.license
24/Aug/2021 09:46:17 [NtopPro.cpp:472] [LICENSE] /etc/ntopng.license: found valid Enterprise L (Bundle) license
[New Thread 0x7fffe53e2700 (LWP 27801)]
[Thread 0x7fffe53e2700 (LWP 27801) exited]
24/Aug/2021 09:46:18 [Redis.cpp:1126] ERR unknown command 'HSTRLEN'
24/Aug/2021 09:46:18 [boot.lua:40] [delete_data_utils.lua:425] Deleting data [delete_if_data][OK]
24/Aug/2021 09:46:18 [boot.lua:40] [delete_data_utils.lua:425] Deleting data [delete_if_ids][OK]
24/Aug/2021 09:46:18 [boot.lua:40] [delete_data_utils.lua:425] Deleting data [delete_if_db][OK]
24/Aug/2021 09:46:18 [boot.lua:40] [delete_data_utils.lua:425] Deleting data [delete_if_redis_keys][OK]
24/Aug/2021 09:46:19 [PcapInterface.cpp:61] Reading packets from pcap file synscan.pcap...
24/Aug/2021 09:46:19 [Ntop.cpp:2601] Registered interface tests/rest/pcap/synscan.pcap [id: 75]
24/Aug/2021 09:46:19 [main.cpp:331] PID stored in file /var/run/ntopng.pid
24/Aug/2021 09:46:19 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
24/Aug/2021 09:46:19 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
24/Aug/2021 09:46:19 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
[New Thread 0x7fffe53e2700 (LWP 27853)]
[New Thread 0x7fffddf9f700 (LWP 27854)]
[New Thread 0x7fffdd783700 (LWP 27855)]
[New Thread 0x7fffdcf67700 (LWP 27856)]
[New Thread 0x7fffdc74b700 (LWP 27857)]
[New Thread 0x7fffdbf27700 (LWP 27858)]
24/Aug/2021 09:46:19 [HTTPserver.cpp:1691] Web server dirs [/home/simone/ntopng/httpdocs][/home/simone/ntopng/scripts]
24/Aug/2021 09:46:19 [HTTPserver.cpp:1694] HTTP server listening on 3000
24/Aug/2021 09:46:19 [Utils.cpp:781] User changed to ntopng
[New Thread 0x7fffdaeb0700 (LWP 27859)]
24/Aug/2021 09:46:19 [NetworkInterface.cpp:2833] Started flow dump loop on interface tests/rest/pcap/synscan.pcap [id: 75]...
24/Aug/2021 09:46:19 [NIndexFlowDB.cpp:121] Successfully open DB /var/lib/ntopng/75/flows
24/Aug/2021 09:46:19 [NIndexFlowDB.cpp:124] [nIndex] Successfully created flow database index [/var/lib/ntopng/75/flows]
[New Thread 0x7fffda6a7700 (LWP 27860)]
24/Aug/2021 09:46:19 [NetworkInterface.cpp:2771] Started flow user script hooks loop on interface tests/rest/pcap/synscan.pcap [id: 75]...
[New Thread 0x7fffd9e83700 (LWP 27861)]
24/Aug/2021 09:46:19 [NetworkInterface.cpp:2802] Started host user script hooks loop on interface tests/rest/pcap/synscan.pcap [id: 75]...
24/Aug/2021 09:46:19 [main.cpp:401] Working directory: /var/lib/ntopng
24/Aug/2021 09:46:19 [main.cpp:403] Scripts/HTML pages directory: /home/simone/ntopng
24/Aug/2021 09:46:19 [Ntop.cpp:479] Welcome to ntopng x86_64 v.5.0.210824 - (C) 1998-21 ntop.org
24/Aug/2021 09:46:19 [Ntop.cpp:489] Built on Ubuntu 16.04.7 LTS
24/Aug/2021 09:46:19 [NtopPro.cpp:763] [LICENSE] System Id:	LA2D7D2FB9206AAF2--UA2D7D2FBDDCCD490--OL
24/Aug/2021 09:46:19 [NtopPro.cpp:764] [LICENSE] Edition:	Enterprise L (Bundle)
24/Aug/2021 09:46:19 [NtopPro.cpp:765] [LICENSE] License Type:	Permanent License
24/Aug/2021 09:46:19 [NtopPro.cpp:774] [LICENSE] License:	XJQ6U04QIW2ixxzNMfGnWibAySvd8Rd3K4qxymrZNT3DoR0m1K6Ybx1nnG1Y1n+7O4znP
24/Aug/2021 09:46:19 [NtopPro.cpp:775] [LICENSE]         	E4Zroy+A5EZZfu/i0UzrOhly/HNUgNju+RTP6d/zAvMTs04ZtIG9/BjalrrOfHzw0bU3u
24/Aug/2021 09:46:19 [NtopPro.cpp:775] [LICENSE]         	Tm0z1F+S5N6IFUP6cXzoWP+yrpGmPjzmQHGa5kSw5IJw6YjmPvAgGLHsKn+u2KoA6xP7c
24/Aug/2021 09:46:19 [NtopPro.cpp:775] [LICENSE]         	4eZ7YGJ/S6MTmYtLFOBse4qoaViSC30RBu54QVG4Zafz4qwhMEnT+hijwbkWJfjZBRzl3
24/Aug/2021 09:46:19 [NtopPro.cpp:775] [LICENSE]         	eLE05HclnkRWibuYJqKG6c9NRExF0u6a3+P/+ouB7PcczDf8G4O22MWgr2cTNjsmRA==
24/Aug/2021 09:46:19 [NtopPro.cpp:779] [LICENSE] License Hash:	CF2C1717835F2782978FFD1C0781E6851643789115097DF1E2
24/Aug/2021 09:46:19 [NtopPro.cpp:790] [LICENSE] Maintenance:	Until Wed Feb  2 09:05:15 2022 [162 days left]
[New Thread 0x7fffd965f700 (LWP 27864)]
[New Thread 0x7fffd8e3b700 (LWP 27865)]
24/Aug/2021 09:46:19 [PeriodicActivities.cpp:107] Started periodic activities loop...
24/Aug/2021 09:46:20 [startup.lua:37] Processing startup.lua: please hold on...
24/Aug/2021 09:46:20 [startup.lua:169] [lists_utils.lua:784] Refreshing category lists...
24/Aug/2021 09:46:20 [startup.lua:169] [lists_utils.lua:717] Category Lists (2164 hosts, 3008 IPs, 100 JA3) loaded in 0 sec
24/Aug/2021 09:46:20 [startup.lua:228] Loading category lists...
24/Aug/2021 09:46:20 [startup.lua:230] Loading category lists done
24/Aug/2021 09:46:20 [startup.lua:288] Completed startup.lua
[New Thread 0x7fffd470e700 (LWP 27877)]
[New Thread 0x7fffd3eea700 (LWP 27878)]
[New Thread 0x7fffd36c6700 (LWP 27879)]
[New Thread 0x7fffd2ea2700 (LWP 27880)]
[New Thread 0x7fffd267e700 (LWP 27881)]
[New Thread 0x7fffd1e5a700 (LWP 27882)]
[New Thread 0x7fffd1636700 (LWP 27883)]
[New Thread 0x7fffd0e12700 (LWP 27884)]
[New Thread 0x7fffd05ee700 (LWP 27885)]
[New Thread 0x7fffcfdca700 (LWP 27886)]
[New Thread 0x7fffcf5a6700 (LWP 27887)]
24/Aug/2021 09:46:20 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
[New Thread 0x7fffced82700 (LWP 27888)]
[New Thread 0x7fffce55e700 (LWP 27889)]
[New Thread 0x7fffcdd2a700 (LWP 27890)]
24/Aug/2021 09:46:20 [NetworkInterface.cpp:2953] Started packet polling on interface tests/rest/pcap/synscan.pcap [id: 75]...
[New Thread 0x7fffcd506700 (LWP 27891)]

Thread 9 "flowdump ifid 7" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdaeb0700 (LWP 27859)]
0x00000000004aef5a in __interceptor_memcmp.part.68 ()
(gdb) bt
#0  0x00000000004aef5a in __interceptor_memcmp.part.68 ()
#1  0x00007ffff33cc278 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000573777 in std::operator< <char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__lhs=<error: Cannot access memory at address 0x4f544f52505f5049>, __rhs="FLOW_TIME")
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/basic_string.h:4989
#3  0x0000000000572fdd in std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (this=0x61200002e6d8, __x=<error: Cannot access memory at address 0x4f544f52505f5049>, __y="FLOW_TIME") at /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/stl_function.h:387
#4  0x000000000136beba in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> > >::_M_lower_bound(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> >*, std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61200002e6d8, __x=0x60700052aed0, __y=0x61200002e6e0, __k="FLOW_TIME") at /usr/include/c++/5/bits/stl_tree.h:1628
#5  0x000000000136b823 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> > >::lower_bound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61200002e6d8, __k="FLOW_TIME") at /usr/include/c++/5/bits/stl_tree.h:1091
#6  0x0000000001367751 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TableColumnDefinition*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> > >::lower_bound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x61200002e6d8, __x="FLOW_TIME")
    at /usr/include/c++/5/bits/stl_map.h:916
#7  0x00000000013629e7 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TableColumnDefinition*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, TableColumnDefinition*> > >::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) (this=0x61200002e6d8, __k=<unknown type in /home/simone/ntopng/ntopng, CU 0x9f7178, DIE 0xa39769>) at /usr/include/c++/5/bits/stl_map.h:499
#8  0x00000000013538e5 in Table::init_write(unsigned int, bool) (this=0x61200002e6c0, _when=1627916927, table_already_open=false) at src/Table.cpp:79
#9  0x000000000135421e in Table::add_row_untyped(unsigned int, void**) (this=0x61200002e6c0, when=1627916927, row_values=0x7fffdaeae220) at src/Table.cpp:259
#10 0x0000000001343fa2 in nindex_add_row(nindex_t, u_int32_t, void**) (t=0x61200002e6c0, when=1627916927, cols=0x7fffdaeae220) at src/nindex_api.cpp:113
#11 0x0000000001217705 in NIndexFlowDB::dumpFlowRow(NIndexFlowInfo*) (this=0x60c0000f4900, nf=0x7fffdaeae940) at pro/NIndexFlowDB.cpp:218
#12 0x000000000121df9a in NIndexFlowDB::dumpFlow(long, Flow*, char*) (this=0x60c0000f4900, when=1627916927, f=0x61a00019da80, json=0x0) at pro/NIndexFlowDB.cpp:427
#13 0x0000000000c184a4 in NetworkInterface::dequeueFlowsForDump(unsigned int, unsigned int) (this=0x621000119500, idle_flows_budget=0, active_flows_budget=131072)
    at src/NetworkInterface.cpp:2722
#14 0x0000000000c19f8f in NetworkInterface::dumpFlowLoop() (this=0x621000119500) at src/NetworkInterface.cpp:2846
#15 0x0000000000c1c5eb in flowDumper(void*) (ptr=0x621000119500) at src/NetworkInterface.cpp:2884
#16 0x00007ffff608d6ba in start_thread (arg=0x7fffdaeb0700) at pthread_create.c:333
#17 0x00007ffff2dd251d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by lucaderi** [comment]
Apparently, the problem shows up only with nIndex without debugging information. Wth sanitizer the crash does not accour but unfortunately, no error is reported. I don't see anything wrong in the nIndex code so for me we can leave it as is until we find a better way to reproduce it.
