### ISSUE TITLE
Adding traffic profiles causes ntopng to hang

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#6114]
Adding a traffic profile that is not recognized as valid, e.g.,  "l7proto Facebook" causes ntopng to say invalid filter. This filter should be valid and this is the first issue.

What happens next is that any other filter addition is impossible: ntopng keeps saying invalid.

After a few attempts, the UI becomes unresponsive with one core spinning at 100%

![image](https://user-images.githubusercontent.com/3397663/144460491-69cc145e-b974-4303-8677-3065ab5d246f.png)

Configuration

![image](https://user-images.githubusercontent.com/3397663/144460523-b7ddf818-392d-4ce6-9a66-953b79df575c.png)

Notes:
- Version 5.1.x
- Disaggregation enabled

**Comment by simonemainardi** [comment]
Seems to be due to a recursive call not terminating

```
#9554 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9555 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9556 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9557 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9558 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9559 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9560 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9561 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9562 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9563 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9564 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9565 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9566 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9567 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9568 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9569 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9570 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9571 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9572 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9573 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9574 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
#9575 0x0000000000a06007 in Ntop::getnDPIProtoByName(char const*) (this=0x62500000c900, name=0x6030005364e0 "facebook") at src/Ntop.cpp:3209
---Type <return> to continue, or q <return> to quit---
```

**Comment by simonemainardi** [comment]
Confirm. Fixed.
