### ISSUE TITLE
ntopng segfault

### ISSUE THREAD

**Issue by puschl** [ntop/ntopng#672]
Hello,
Current nightly produces an segfault.
Version: ntopng x86_64 v.2.5.160802
[core.17752.gz](https://github.com/ntop/ntopng/files/396891/core.17752.gz)
[core.17688.gz](https://github.com/ntop/ntopng/files/396892/core.17688.gz)

See below:

```
[root@ntop-ng ntopng]# gdb /usr/bin/ntopng core.17752                 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/ntopng...done.
[New LWP 17752]
[New LWP 17754]
[New LWP 17756]
[New LWP 17755]
[New LWP 17757]
[New LWP 17760]
[New LWP 17761]
[New LWP 17765]
[New LWP 17763]
[New LWP 17766]
[New LWP 17767]
[New LWP 17764]
[New LWP 17762]
[New LWP 17758]
[New LWP 17759]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `ntopng /etc/ntopng/ntopng.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004e4775 in lj_err_optype (L=0x4094f378, o=0x409507d8, opm=LJ_ERR_OPCALL) at lj_err.c:607
607     lj_err.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install ntopng-2.5.160802-1389.x86_64
(gdb) bt
#0  0x00000000004e4775 in lj_err_optype (L=0x4094f378, o=0x409507d8, opm=LJ_ERR_OPCALL) at lj_err.c:607
#1  0x00000000004e4a17 in lj_err_optype_call (L=0x4094f378, o=0x409507d8) at lj_err.c:642
#2  0x00000000005167c1 in lj_meta_call (L=0x4094f378, func=0x409507d8, top=0x409507e0) at lj_meta.c:432
#3  0x000000000050dfe8 in lj_vmeta_call ()
#4  0x00000000004ef64f in lua_pcall (L=0x4094f378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1052
#5  0x0000000000450133 in NetworkInterface::luaEvalFlow (this=0x2080b20, f=0x7fc34f1b4820, luaFunction=0x5b0d17 "flowUpdate") at src/NetworkInterface.cpp:3544
#6  0x000000000043919e in Flow::update_hosts_stats (this=0x7fc34f1b4820, tv=0x7ffcc43bf6e0) at src/Flow.cpp:838
#7  0x000000000044a3bb in flow_update_hosts_stats (node=0x7fc34f1b4820, user_data=0x7ffcc43bf6e0) at src/NetworkInterface.cpp:1650
#8  0x000000000042bd72 in GenericHash::walk (this=0x2081960, walker=0x44a388 <flow_update_hosts_stats(GenericHashEntry*, void*)>, user_data=0x7ffcc43bf6e0) at src/GenericHash.cpp:153
#9  0x000000000044a435 in NetworkInterface::updateHostStats (this=0x2080b20) at src/NetworkInterface.cpp:1677
#10 0x000000000044dff2 in NetworkInterface::runHousekeepingTasks (this=0x2080b20) at src/NetworkInterface.cpp:2816
#11 0x000000000048373a in Ntop::runHousekeepingTasks (this=0x207c600) at src/Ntop.cpp:1300
#12 0x0000000000480ab1 in Ntop::start (this=0x207c600) at src/Ntop.cpp:310
#13 0x000000000047837d in main (argc=2, argv=0x7ffcc43bfa98) at src/main.cpp:339
(gdb) info threads
  Id   Target Id         Frame 
  15   Thread 0x7fc36ffff700 (LWP 17759) 0x00007fc37fa2b6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  14   Thread 0x7fc374b5e700 (LWP 17758) 0x00007fc37fa2b6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  13   Thread 0x7fc36e7fc700 (LWP 17762) 0x00007fc37b09defd in nanosleep () from /lib64/libc.so.6
  12   Thread 0x7fc36d7fa700 (LWP 17764) 0x00007fc37b09defd in nanosleep () from /lib64/libc.so.6
  11   Thread 0x7fc3677fe700 (LWP 17767) 0x00007fc37b09defd in nanosleep () from /lib64/libc.so.6
  10   Thread 0x7fc367fff700 (LWP 17766) 0x00007fc37b09defd in nanosleep () from /lib64/libc.so.6
  9    Thread 0x7fc36dffb700 (LWP 17763) 0x00007fc37b09defd in nanosleep () from /lib64/libc.so.6
  8    Thread 0x7fc36cff9700 (LWP 17765) 0x0000000000435f66 in Flow::Flow (this=0x7fc34f2dc430, _iface=0x2080b20, _vlanId=1254, _protocol=6 '\006', 
    cli_mac=0x7fc3767cc276 <Address 0x7fc3767cc276 out of bounds>, _cli_ip=0x7fc36cff8a00, _cli_port=47418, srv_mac=0x7fc3767cc270 <Address 0x7fc3767cc270 out of bounds>, _srv_ip=0x7fc36cff89e0, 
    _srv_port=63694, _first_seen=0, _last_seen=0) at src/Flow.cpp:53
  7    Thread 0x7fc36effd700 (LWP 17761) 0x00007fc37b09defd in nanosleep () from /lib64/libc.so.6
  6    Thread 0x7fc36f7fe700 (LWP 17760) 0x00007fc37fa2b6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7fc37535f700 (LWP 17757) 0x00007fc37fa2b6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  4    Thread 0x7fc376361700 (LWP 17755) 0x00007fc37b0cc69d in poll () from /lib64/libc.so.6
  3    Thread 0x7fc375b60700 (LWP 17756) 0x00007fc37fa2b6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  2    Thread 0x7fc37721d700 (LWP 17754) 0x00007fc37fa2e22d in read () from /lib64/libpthread.so.0
* 1    Thread 0x7fc3813ff880 (LWP 17752) 0x00000000004e4775 in lj_err_optype (L=0x4094f378, o=0x409507d8, opm=LJ_ERR_OPCALL) at lj_err.c:607
(gdb) 
```

**Comment by lucaderi** [comment]
@puschl What Linux distro are you using? What ntopng binary package have you used?

**Comment by puschl** [comment]
@lucaderi 
CentOS Linux release 7.2.1511 (Core) 
Binary was nightly from today.
Taken via yum from http://packages.ntop.org/centos/

**Comment by lucaderi** [comment]
@puschl Please upgrade and report if working now.

**Comment by lucaderi** [comment]
Seems to be solved. Please reopen it if necessary.

**Comment by lucaderi** [comment]
The above fix was also necessary and ntopng should now be stable. Please confirm.
