### ISSUE TITLE
Crashes on daemonizing.

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#8032]
**Environment**:
* OS name: Slackware
* OS version: 15.0
* Architecture: x86_64
* ntopng version/revision: dc19d2aadaff7c4ee5afb033748bbf5172af8f7a

**What happened**:

On running `/usr/bin/ntopng -w 127.0.0.1:3000 --interface=eth2 --interface=wlan1 --disable-login=1 --user=ntopng --daemon --pid=/var/run/ntopng.pid`, the parent process crashes on exit.

bt:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7663aad in genl_unregister () from /usr/lib64/libnl.so.1
(gdb) bt
#0  0x00007ffff7663aad in genl_unregister () at /usr/lib64/libnl.so.1
#1  0x00007ffff7fdd734 in _dl_fini () at /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff6e5f4c7 in __run_exit_handlers () at /lib64/libc.so.6
#3  0x00007ffff6e5f66a in  () at /lib64/libc.so.6
#4  0x000000000053c7a8 in Ntop::daemonize() (this=0x88a890) at src/Ntop.cpp:2645
#5  0x00000000005b4deb in main(int, char**) (argc=9, argv=0x7fffffffd9e8) at src/main.cpp:169
```
That line is:
`      exit(0);`

**How did you reproduce it?**
Compile and run like this:
```
./autogen.sh
./configure \
  --prefix=/usr \
  --datadir=/usr/share \
  --libdir=/usr/lib64 \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/ntopng-6.0 \
  --disable-static \
  --build=x86_64-slackware-linux
sed -i 's|-lhiredis|-lhiredis -lpcre|g' Makefile

make
make install DESTDIR=$PKG
```

**Debug Information**:

Logs do not indicate anything. Parent's log:
```
21/Nov/2023 10:44:35 [Prefs.cpp:1725] All HTTP user login disabled
21/Nov/2023 10:44:35 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Nov/2023 10:44:35 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Nov/2023 10:44:39 [Ntop.cpp:2597] Parent process is exiting (this is normal)
21/Nov/2023 10:49:35 [Prefs.cpp:1725] All HTTP user login disabled
21/Nov/2023 10:49:35 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Nov/2023 10:49:35 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Nov/2023 10:49:35 [ThreadedActivity.cpp:272] WARNING: Unable to find script boot.lua
21/Nov/2023 10:49:35 [Ntop.cpp:2597] Parent process is exiting (this is normal)
21/Nov/2023 10:50:22 [Prefs.cpp:1725] All HTTP user login disabled
21/Nov/2023 10:50:22 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Nov/2023 10:50:22 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Nov/2023 10:50:25 [Ntop.cpp:2597] Parent process is exiting (this is normal)
```

Child's log:
```
21/Nov/2023 10:34:13 [Ntop.cpp:1065] Adding <snip> as IPv6 interface address for eth2
21/Nov/2023 10:34:13 [Ntop.cpp:1077] Adding <snip> as IPv6 local network for eth2
21/Nov/2023 10:34:13 [Ntop.cpp:1065] Adding <snip> as IPv6 interface address for eth2
21/Nov/2023 10:34:13 [Ntop.cpp:1077] Adding <snip>/64 as IPv6 local network for eth2
21/Nov/2023 10:34:13 [PeriodicActivities.cpp:108] Started periodic activities loop...
21/Nov/2023 10:34:13 [ThreadedActivity.cpp:272] WARNING: Unable to find script startup.lua
21/Nov/2023 10:34:13 [PeriodicActivities.cpp:167] Found 10 activities
21/Nov/2023 10:34:13 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
21/Nov/2023 10:34:13 [NetworkInterface.cpp:3708] Started packet polling on interface wlan1 [id: 1]...
21/Nov/2023 10:34:13 [NetworkInterface.cpp:3708] Started packet polling on interface eth2 [id: 7]...
```

**Comment by lucaderi** [comment]
Unable to reproduce on Linux distro we use with the code in github
